### ISSUE TITLE
Homebridge stuck on reboot loop after Update to latetst beta.

### ISSUE THREAD

**Issue by Feinfinger380** [justme-1968/homebridge-fhem#103]
I use homebridge version 1.8.4. After the update to latest beta via the web interface, the homebridge gets stuck in a reboot loop.
As soon as I install the last stable version via the console, it works perfectly again.

`[9/20/2024, 4:48:36 AM] TypeError: Cannot read properties of undefined (reading 'UINT8')
    at FHEMAccessory.getServices (/usr/local/lib/node_modules/homebridge-fhem/index.js:3143:101)
    at BridgeService.createHAPAccessory (file:///usr/local/lib/node_modules/homebridge/src/bridgeService.ts:439:41)
    at file:///usr/local/lib/node_modules/homebridge/src/bridgeService.ts:509:34
    at Array.forEach (<anonymous>)
    at file:///usr/local/lib/node_modules/homebridge/src/bridgeService.ts:500:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:14
    at FHEMPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:1222:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:313:12)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1638:10)
    at Request.emit (node:events:519:28)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1509:12)
    at Object.onceWrapper (node:events:633:28)
    at Gunzip.emit (node:events:519:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[9/20/2024, 4:48:36 AM] Got SIGTERM, shutting down Homebridge...
[9/20/2024, 4:48:36 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:897:11)
    at Server.setServerStatus (file:///usr/local/lib/node_modules/homebridge/src/server.ts:146:45)
    at Server.teardown (file:///usr/local/lib/node_modules/homebridge/src/server.ts:190:10)
    at signalHandler (file:///usr/local/lib/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[9/20/2024, 4:48:36 AM] [Homebridge UI] Homebridge UI v4.58.0 is listening on :: port 8080

Websocket failed to connect. Is the server running?`

Here´s the config:

`{
    "bridge": {
        "name": "Homebridge FHEM",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "000-00-000"
    },
    "platforms": [
        {
            "platform": "FHEM",
            "name": "FHEM",
            "server": "XXX.XXX.XXX.X",
            "auth": {
                "user": "XXXXXX",
                "pass": "XXXXXXXXXXXXX"
            },
            "port": "8083",
            "filter": "room=Homekit"
        },
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "blue",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "debug": false,
            "log": {
                "method": "custom",
                "command": "journalctl -o cat -n 500 -f -u homebridge"
            },
            "accessoryControl": {
                "debug": false,
                "instanceBlacklist": [
                    "XX:XX:XX:XX:XX:XX",
                    "XX:XX:XX:XX:XX:XX",
                    "XX:XX:XX:XX:XX:XX",
                    "XX:XX:XX:XX:XX:XX"
                ]
            },
            "platform": "config"
        }
    ],
    "accessories": [],
    "id": "config"
}`

`Environment

    OS: Ubuntu 20.04.6 LTS
    Software: Homebridge 1.8.4
    Node: 20.17.0
    npm: 10.8.2
`

**Comment by bircni** [comment]
And what is the Problem With the fhem Plugin?

**Comment by bircni** [comment]
Seems Like some accessory is not published...

**Comment by Feinfinger380** [comment]
What is strange, however, is that on the test system I use, the fhem plugin works with the latest homebridge 2.0 beta.

**Comment by mrpointblue** [comment]
Same Problem homebridge-fhem ends and goes in loop. Looks like a problem with callback ?
Log is bigger than 25MB.

>>

`[19/11/2024, 01:26:10] [FHEM] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
[19/11/2024, 01:26:10] [FHEM] Child bridge will automatically restart in 40 seconds (restart attempt 4 of 4).

>>

/var/lib/homebridge/node_modules/homebridge-fhem/index.js:2705
                        callback(undefined, value);
                        ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at FHEMAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fhem/index.js:2705:25)
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-fhem/index.js:1081:27)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-fhem/node_modules/postman-request/request.js:313:12)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1638:10)
    at Request.emit (node:events:519:28)
    at Gunzip.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1509:12)
    at Object.onceWrapper (node:events:633:28)
    at Gunzip.emit (node:events:519:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[19/11/2024, 01:27:41] [FHEM] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
[19/11/2024, 01:27:41] [FHEM] Child bridge will no longer restart after failing 5 times, you will need to manually start this child bridge from the Homebridge UI.

**Comment by justme-1968** [comment]
the latest version should work with the v2 beta

**Comment by mrpointblue** [comment]
I'm not quite sure, in any case this has appeared since the new Fehm version. Unfortunately, I am not a professional to interpret this exactly. The error occurs permanently and can no longer be rectified even after a downgrade.
