### ISSUE TITLE
Same Problem homebridge-fhem ends and goes in loop. Looks like a problem with callback ?

### ISSUE THREAD

**Issue by justme-1968** [justme-1968/homebridge-fhem#104]
Same Problem homebridge-fhem ends and goes in loop. Looks like a problem with callback ?
Log is bigger than 25MB.

>>

`[19/11/2024, 01:26:10] [FHEM] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
[19/11/2024, 01:26:10] [FHEM] Child bridge will automatically restart in 40 seconds (restart attempt 4 of 4).

>>

/var/lib/homebridge/node_modules/homebridge-fhem/index.js:2705
                        callback(undefined, value);
                        ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at FHEMAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fhem/index.js:2705:25)
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-fhem/index.js:1081:27)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-fhem/node_modules/postman-request/request.js:313:12)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1638:10)
    at Request.emit (node:events:519:28)
    at Gunzip.<anonymous> (/var/lib/homebridge/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1509:12)
    at Object.onceWrapper (node:events:633:28)
    at Gunzip.emit (node:events:519:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[19/11/2024, 01:27:41] [FHEM] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
[19/11/2024, 01:27:41] [FHEM] Child bridge will no longer restart after failing 5 times, you will need to manually start this child bridge from the Homebridge UI.

_Originally posted by @mrpointblue in https://github.com/justme-1968/homebridge-fhem/issues/103#issuecomment-2484456562_

**Comment by justme-1968** [comment]
@mrpointblue : not the same problem. is this reproducible ?

**Comment by mrpointblue** [comment]
I can't say that, it's permanent. After updating nodeJS and upgrading to Homebridge 2.0 the problem still persists.

**Comment by mrpointblue** [comment]
Problem found / solved: The FirmwareRevision mapping causes a crash due to ambiguous values ​​being found. I have removed this from all devices. Now no more crash.
