### ISSUE TITLE
TypeError after update

### ISSUE THREAD

**Issue by meilon** [justme-1968/homebridge-fhem#14]
Hi!

after updating to the current 0.2.33 of homebridge-fhem (from I think 0.2.31) I get a TypeError upon start:

```
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[8/25/2016, 11:08:34 AM] Loaded plugin: homebridge-fhem
homebridge API version: 2
[8/25/2016, 11:08:34 AM] Registering platform 'homebridge-fhem.FHEM'
[8/25/2016, 11:08:34 AM] ---
[8/25/2016, 11:08:34 AM] Loaded config.json with 0 accessories and 1 platforms.
[8/25/2016, 11:08:34 AM] ---
[8/25/2016, 11:08:34 AM] Loading 1 platforms...
[8/25/2016, 11:08:34 AM] [FHEM] Initializing FHEM platform...
starting longpoll: http://127.0.0.1:8083/fhem.pl?XHR=1&inform=type=status;addglobal=1;filter=.*;since=null;fmt=JSON&timestamp=1472116116244
[8/25/2016, 11:08:36 AM] [FHEM] Checking genericDeviceType...
[8/25/2016, 11:08:36 AM] [FHEM]   executing: http://127.0.0.1:8083/fhem?cmd=%7BAttrVal(%22global%22,%22userattr%22,%22%22)%7D&XHR=1
[8/25/2016, 11:08:36 AM] [FHEM] Fetching FHEM devices...
[8/25/2016, 11:08:36 AM] [FHEM] fetching: http://127.0.0.1:8083/fhem?cmd=jsonlist2%20room=Homekit&XHR=1
[8/25/2016, 11:08:36 AM] Loading 0 accessories...
Server listening on: http://<ip>:8282
[8/25/2016, 11:08:38 AM] [FHEM] got: 5 results
/usr/lib/node_modules/homebridge-fhem/index.js:1555
    if( match[3] ) {
             ^

TypeError: Cannot read property '3' of null
    at Object.FHEMAccessory (/usr/lib/node_modules/homebridge-fhem/index.js:1555:14)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-fhem/index.js:975:42)
    at Array.map (native)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-fhem/index.js:972:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-fhem/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
```

Because something changed with the homematic part of your code I removed all thermostats from the HomeKit room and homebrige started up fine. After adding just one I got the same error again.

This is the data I get from curl-ing the jsonlist URL with the HTML bits removed:

```
{
  "Arg":"room=Homekit",
  "Results": [
  {
    "Name":"WZ_SW_Desklamp",
    "PossibleSets":"associationAdd associationDel configActionInCaseOfExceedingDefined52:TurnTheAssociatedDevicesOnPower1,TurnTheAssociatedDevicesOffPower2,1And4Combine,TurnTheAssociatedDevicesOffPower4,TurnTheAssociatedDevicesOnPower3,2And3Combined,FunctionInactive configAlarmDuration configAlwaysOnFunction:functionInactive,functionActivated configByte configDOWNValue configDefault configImmediatePowerReport configLEDRingIlluminationColourAtTheZ63:RedIllumination,MagentaIllumination,YellowIllumination,GreenIllumination,WhiteIllumination,NoChangeInColour,LEDRingFlashesRedBlueWhite,BlueIllumination,illuminationTurnedOffCompletely,CyanIlluminatio configLEDRingIlluminationColourWhen61:BlueIllumination,DependingOnPowerConsumption0,CyanIlluminatio,illuminationTurnedOffCompletely,GreenIllumination,WhiteIllumination,MagentaIllumination,YellowIllumination,RedIllumination,UsingFullSpectrumOfAvailable1 configLEDRingIlluminationColourWhen62:WhiteIllumination,GreenIllumination,CyanIlluminatio,illuminationTurnedOffCompletely,DependingOnTheLastMeasuredPower,BlueIllumination,RedIllumination,YellowIllumination,MagentaIllumination configLong configMeteringEnergyConsumedByTheWall49:functionInactive,functionActivated configOveloadSafetySwitch configPowerLoadWhichWhenExceededMakes60 configPowerReportingFrequency configReactionToAlarms:ALARMCO,ALARMWATER,ALARMSMOKE,ALARMHEAT,ALARMALL,ALARMGENERIC,ALARMCO2 configRememberDeviceStatusAfterPower16:WallPlugMemorizesItsStateAfterA1,WallPlugDoesNotMemorizeItsState0 configReportingChangesInEnergyConsumed45 configStandardPowerLoadReporting configTimePeriodBetweenReportsOnPower47 configUPValue configWallPlugSResponseToAlarmFrames:TurnOnConnectedDevice,CyclicallyChangeDeviceState3,TurnOffConnectedDevice,NoReaction configWord mcaAdd mcaDel meterReset:noArg neighborUpdate:noArg off:noArg on:noArg powerlevel powerlevelTest returnRouteAdd returnRouteDel:noArg on-till toggle on-for-timer off-till-overnight off-till on-till-overnight intervals off-for-timer blink",
    "PossibleAttrs":"verbose:0,1,2,3,4,5 room group comment:textField-long alias eventMap userReadings:textField-long IODev WNMI_delay noWakeupForApplicationUpdate:1,0 classes do_not_notify:1,0 dummy:1,0 extendedAlarmReadings:0,1,2 ignore:1,0 noExplorerFrames:1,0 eventForRaw secure_classes showtime:1,0 vclasses zwaveRoute neighborListPos event-on-change-reading event-on-update-reading event-aggregator event-min-interval stateFormat:textField-long timestamp-on-change-reading alarmDevice alarmSettings cmdIcon devStateIcon devStateStyle fm_type genericDeviceType:switch,outlet,light,blind,speaker,thermostat homebridgeMapping:textField-long icon sortby webCmd widgetOverride userattr",
    "Internals": {
      "DEF": "f154c3aa 5",
      "NAME": "WZ_SW_Desklamp",
      "NR": "111",
      "STATE": "off",
      "TYPE": "ZWave",
      "ZWaveSubDevice": "no",
      "homeId": "f154c3aa",
      "nodeIdHex": "05"
    },
    "Readings": {
      "configActionInCaseOfExceedingDefined52": { "Value":"2And3Combined", "Time":"2016-08-17 18:44:55" },
      "configAlarmDuration": { "Value":"600", "Time":"2016-08-17 18:44:55" },
      "configAlwaysOnFunction": { "Value":"functionInactive", "Time":"2016-08-17 18:44:55" },
      "configDOWNValue": { "Value":"300", "Time":"2016-08-17 18:44:55" },
      "configImmediatePowerReport": { "Value":"80", "Time":"2016-08-17 18:44:55" },
      "configLEDRingIlluminationColourAtTheZ63": { "Value":"LEDRingFlashesRedBlueWhite", "Time":"2016-08-17 18:44:55" },
      "configLEDRingIlluminationColourWhen61": { "Value":"illuminationTurnedOffCompletely", "Time":"2016-08-17 18:44:55" },
      "configLEDRingIlluminationColourWhen62": { "Value":"illuminationTurnedOffCompletely", "Time":"2016-08-17 18:44:55" },
      "configMeteringEnergyConsumedByTheWall49": { "Value":"functionInactive", "Time":"2016-08-17 18:44:55" },
      "configOveloadSafetySwitch": { "Value":"65535", "Time":"2016-08-17 18:44:55" },
      "configPowerLoadWhichWhenExceededMakes60": { "Value":"25000", "Time":"2016-08-17 18:44:55" },
      "configPowerReportingFrequency": { "Value":"30", "Time":"2016-08-17 18:44:55" },
      "configReactionToAlarms": { "Value":"ALARMALL", "Time":"2016-08-17 18:44:55" },
      "configRememberDeviceStatusAfterPower16": { "Value":"WallPlugMemorizesItsStateAfterA1", "Time":"2016-08-17 18:44:55" },
      "configReportingChangesInEnergyConsumed45": { "Value":"10", "Time":"2016-08-17 18:44:55" },
      "configStandardPowerLoadReporting": { "Value":"15", "Time":"2016-08-17 18:44:55" },
      "configTimePeriodBetweenReportsOnPower47": { "Value":"3600", "Time":"2016-08-17 18:44:55" },
      "configUPValue": { "Value":"500", "Time":"2016-08-17 18:44:55" },
      "configWallPlugSResponseToAlarmFrames": { "Value":"NoReaction", "Time":"2016-08-17 18:44:55" },
      "energy": { "Value":"0.57 kWh", "Time":"2016-08-25 10:21:27" },
      "meterSupported": { "Value":"type: energy scales: 0:kWh, 2:W resetable: yes", "Time":"2016-08-17 18:46:07" },
      "model": { "Value":"FIBARO System FGWPE Wall Plug", "Time":"2016-08-17 18:16:22" },
      "modelConfig": { "Value":"fibaro/fgwpe.xml", "Time":"2016-08-17 18:16:22" },
      "modelId": { "Value":"010f-0600-1000", "Time":"2016-08-17 18:16:22" },
      "power": { "Value":"0.0 W", "Time":"2016-08-25 10:53:53" },
      "powerlvl": { "Value":"current 0 remain 0", "Time":"2016-08-17 18:45:54" },
      "reportedState": { "Value":"off", "Time":"2016-08-17 18:21:49" },
      "state": { "Value":"off", "Time":"2016-08-24 21:53:54" },
      "timeToAck": { "Value":"0.031", "Time":"2016-08-24 21:53:54" },
      "transmit": { "Value":"OK", "Time":"2016-08-24 21:53:54" }
    },
    "Attributes": {
      "IODev": "ZWDongle_1",
      "alias": "Schreibtischlampe",
      "classes": "MANUFACTURER_SPECIFIC VERSION CONFIGURATION ASSOCIATION MULTI_CHANNEL_ASSOCIATION SWITCH_BINARY POWERLEVEL METER SENSOR_MULTILEVEL FIRMWARE_UPDATE_MD MARK SWITCH_BINARY METER SENSOR_MULTILEVEL",
      "genericDeviceType": "light",
      "room": "Wohnzimmer,ZWave,Homekit",
      "vclasses": "ASSOCIATION:2 CONFIGURATION:1 FIRMWARE_UPDATE_MD:1 MANUFACTURER_SPECIFIC:1 METER:2 MULTI_CHANNEL_ASSOCIATION:2 POWERLEVEL:1 SENSOR_MULTILEVEL:2 SWITCH_BINARY:1 VERSION:1"
    }
  },
  {
    "Name":"WZ_TM_Clima",
    "PossibleSets":"burstXmit clear:readings,trigger,register,oldRegs,rssi,msgEvents,attack,all controlManu:on,off,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0,15.5,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,22.0,22.5,23.0,23.5,24.0,24.5,25.0,25.5,26.0,26.5,27.0,27.5,28.0,28.5,29.0,29.5,30.0 controlMode:auto,manual,boost,day,night controlParty desired-temp:on,off,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0,15.5,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,22.0,22.5,23.0,23.5,24.0,24.5,25.0,25.5,26.0,26.5,27.0,27.5,28.0,28.5,29.0,29.5,30.0 getConfig getRegRaw inhibit:on,off peerBulk regBulk regSet sign:on,off sysTime tempListFri tempListMon tempListSat tempListSun tempListThu tempListTmpl tempListTue tempListWed tempTmplSet:none,defaultWeekplan,BZ.TM.Klima,WZ.TM.Klima ",
    "PossibleAttrs":"verbose:0,1,2,3,4,5 room group comment:textField-long alias eventMap userReadings:textField-long do_not_notify:1,0 showtime:1,0 rawToReadable unit expert:0_defReg,1_allReg,2_defReg+raw,3_allReg+raw,4_off,8_templ+default,12_templOnly,251_anything param actAutoTry:0_off,1_on aesCommReq:1,0 ignore:1,0 dummy:1,0 IODev IOList IOgrp rssiLog:1,0 actCycle hmKey hmKey2 hmKey3 serialNr firmware .stc .devInfo actStatus autoReadReg:0_off,1_restart,2_pon-restart,3_onChange,4_reqStatus,5_readMissing,8_stateOnly burstAccess:0_off,1_auto msgRepeat hmProtocolEvents:0_off,1_dump,2_dumpFull,3_dumpTrigger aesKey:5,4,3,2,1,0  repPeers peerIDs tempListTmpl:none,defaultWeekplan,BZ.TM.Klima,WZ.TM.Klima levelRange levelMap event-on-change-reading event-on-update-reading event-aggregator event-min-interval stateFormat:textField-long timestamp-on-change-reading model:ASH550,ASH550I,CCU-FHEM,CMM,DORMA_BRC-H,DORMA_RC-H,DORMA_atent,HM-CC-RT-DN,HM-CC-RT-DN-BoM,HM-CC-SCD,HM-CC-TC,HM-CC-VD,HM-Dis-EP-WM55,HM-Dis-TD-T,HM-Dis-WM55,HM-ES-PMSw1-DR,HM-ES-PMSw1-Pl,HM-ES-PMSw1-Pl-DN-R1,HM-ES-PMSw1-Pl-DN-R2,HM-ES-PMSw1-Pl-DN-R3,HM-ES-PMSw1-Pl-DN-R4,HM-ES-PMSw1-Pl-DN-R5,HM-ES-PMSw1-SM,HM-ES-TX-WM,HM-LC-AO-SM,HM-LC-BL1-FM,HM-LC-BL1-PB-FM,HM-LC-BL1-SM,HM-LC-Bl1-FM-2,HM-LC-Bl1-SM-2,HM-LC-Bl1PBU-FM,HM-LC-DDC1-PCB,HM-LC-DIM1L-CV,HM-LC-DIM1L-PL,HM-LC-DIM1T-CV,HM-LC-DIM1T-FM,HM-LC-DIM1T-PL,HM-LC-DIM2L-CV,HM-LC-DIM2L-SM,HM-LC-DIM2T-SM,HM-LC-Dim1L-CV-2,HM-LC-Dim1L-CV-644,HM-LC-Dim1L-Pl-2,HM-LC-Dim1L-Pl-3,HM-LC-Dim1L-Pl-644,HM-LC-Dim1PWM-CV,HM-LC-Dim1PWM-CV-2,HM-LC-Dim1T-CV-2,HM-LC-Dim1T-CV-644,HM-LC-Dim1T-FM-2,HM-LC-Dim1T-FM-644,HM-LC-Dim1T-FM-LF,HM-LC-Dim1T-Pl-2,HM-LC-Dim1T-Pl-3,HM-LC-Dim1T-Pl-644,HM-LC-Dim1TPBU-FM,HM-LC-Dim1TPBU-FM-2,HM-LC-Dim2L-SM-2,HM-LC-Dim2L-SM-644,HM-LC-Dim2T-SM,HM-LC-Dim2T-SM-2,HM-LC-RGBW-WM,HM-LC-SW1-BA-PCB,HM-LC-SW1-FM,HM-LC-SW1-PB-FM,HM-LC-SW1-PL,HM-LC-SW1-PL-OM54,HM-LC-SW1-PL2,HM-LC-SW1-SM,HM-LC-SW1-SM-ATMEGA168,HM-LC-SW2-DR,HM-LC-SW2-FM,HM-LC-SW2-PB-FM,HM-LC-SW2-SM,HM-LC-SW4-BA-PCB,HM-LC-SW4-DR,HM-LC-SW4-PCB,HM-LC-SW4-SM,HM-LC-SW4-SM-ATMEGA168,HM-LC-SW4-WM,HM-LC-Sw1-DR,HM-LC-Sw1-FM-2,HM-LC-Sw1-PCB,HM-LC-Sw1-Pl-3,HM-LC-Sw1-Pl-CT-R1,HM-LC-Sw1-Pl-CT-R2,HM-LC-Sw1-Pl-CT-R3,HM-LC-Sw1-Pl-CT-R4,HM-LC-Sw1-Pl-CT-R5,HM-LC-Sw1-Pl-DN-R1,HM-LC-Sw1-Pl-DN-R2,HM-LC-Sw1-Pl-DN-R3,HM-LC-Sw1-Pl-DN-R4,HM-LC-Sw1-Pl-DN-R5,HM-LC-Sw1-SM-2,HM-LC-Sw1PBU-FM,HM-LC-Sw2-DR-2,HM-LC-Sw2-FM-2,HM-LC-Sw2PBU-FM,HM-LC-Sw4-DR-2,HM-LC-Sw4-PCB-2,HM-LC-Sw4-SM-2,HM-LC-Sw4-WM-2,HM-MOD-Em-8,HM-MOD-Re-8,HM-OU-CF-PL,HM-OU-CFM-PL,HM-OU-CFM-TW,HM-OU-CM-PCB,HM-OU-LED16,HM-PB-2-FM,HM-PB-2-WM,HM-PB-2-WM55,HM-PB-2-WM55-2,HM-PB-4-WM,HM-PB-4DIS-WM,HM-PB-4DIS-WM-2,HM-PB-6-WM55,HM-PBI-4-FM,HM-RC-12,HM-RC-12-B,HM-RC-12-SW,HM-RC-19,HM-RC-19-B,HM-RC-19-SW,HM-RC-2-PBU-FM,HM-RC-4,HM-RC-4-2,HM-RC-4-3,HM-RC-4-3-D,HM-RC-4-B,HM-RC-8,HM-RC-Dis-H-x-EU,HM-RC-KEY3,HM-RC-KEY3-B,HM-RC-Key4-2,HM-RC-Key4-3,HM-RC-P1,HM-RC-SEC3,HM-RC-SEC3-B,HM-RC-Sec4-2,HM-RC-Sec4-3,HM-SCI-3-FM,HM-SEC-KEY,HM-SEC-KEY-O,HM-SEC-KEY-S,HM-SEC-MDIR,HM-SEC-MDIR-2,HM-SEC-MDIR-3,HM-SEC-RHS,HM-SEC-RHS-2,HM-SEC-SC,HM-SEC-SC-2,HM-SEC-SCo,HM-SEC-SD,HM-SEC-SD-2,HM-SEC-SFA-SM,HM-SEC-TIS,HM-SEC-WDS,HM-SEC-WDS-2,HM-SEC-WIN,HM-SEN-EP,HM-SEN-MDIR-SM,HM-SWI-3-FM,HM-Sec-Cen,HM-Sec-Sir-WM,HM-Sen-DB-PCB,HM-Sen-LI-O,HM-Sen-MDIR-O,HM-Sen-MDIR-O-2,HM-Sen-MDIR-WM55,HM-Sen-RD-O,HM-Sen-Wa-Od,HM-Sys-sRP-Pl,HM-TC-IT-WM-W-EU,HM-WDC7000,HM-WDS10-TH-O,HM-WDS100-C6-O,HM-WDS100-C6-O-2,HM-WDS20-TH-O,HM-WDS30-OT2-SM,HM-WDS30-OT2-SM-2,HM-WDS30-T-O,HM-WDS40-TH-I,HM-WDS40-TH-I-2,HM-WS550,HM-WS550LCB,HM-WS550LCW,HM-WS550Tech,IS-WDS-TH-OD-S-R3,KFM-Display,KFM-Sensor,KS550,KS550LC,KS550TECH,KS888,OLIGO-smart-iq-HM,PS-Th-Sens,PS-switch,ROTO_ZEL-STG-RM-DWT-10,ROTO_ZEL-STG-RM-FDK,ROTO_ZEL-STG-RM-FEP-230V,ROTO_ZEL-STG-RM-FSA,ROTO_ZEL-STG-RM-FST-UP4,ROTO_ZEL-STG-RM-FWT,ROTO_ZEL-STG-RM-FZS,ROTO_ZEL-STG-RM-FZS-2,ROTO_ZEL-STG-RM-HS-4,ROTO_ZEL-STG-RM-WT-2,Roto_ZEL-STG-RM-FFK,Roto_ZEL-STG-RM-FSS-UP3,S550IA,Schueco_263-130,Schueco_263-131,Schueco_263-132,Schueco_263-133,Schueco_263-134,Schueco_263-135,Schueco_263-144,Schueco_263-145,Schueco_263-146,Schueco_263-147,Schueco_263-155,Schueco_263-157,Schueco_263-158,Schueco_263-160,Schueco_263-162,Schueco_263-167,Schueco_263-xxx,SensoTimer-ST-6,WDF-solar,WS888 subType:AlarmControl,KFM100,THSensor,blindActuator,blindActuatorSol,dimmer,keyMatic,motionAndBtn,motionDetector,outputUnit,powerMeter,powerSensor,pushButton,remote,repeater,rgb,senBright,sensRain,sensor,singleButton,siren,smokeDetector,swi,switch,thermostat,threeStateSensor,timer,tipTronic,virtual,winMatic alarmDevice alarmSettings cmdIcon devStateIcon devStateStyle fm_type genericDeviceType:switch,outlet,light,blind,speaker,thermostat homebridgeMapping:textField-long icon sortby webCmd widgetOverride userattr",
    "Internals": {
      "DEF": "3A8B5B04",
      "NAME": "WZ_TM_Clima",
      "NOTIFYDEV": "global",
      "NR": "71",
      "NTFY_ORDER": "50-WZ_TM_Clima",
      "STATE": "T: 22.0 desired: 10.0 valve: 0",
      "TYPE": "CUL_HM",
      "chanNo": "04",
      "device": "WZ_TM"
    },
    "Readings": {
      "CommandAccepted": { "Value":"yes", "Time":"2016-08-23 16:43:13" },
      "R-boostPos": { "Value":"80 %", "Time":"2015-12-13 21:29:14" },
      "R-btnNoBckLight": { "Value":"off", "Time":"2015-12-13 21:29:14" },
      "R-dayTemp": { "Value":"21 C", "Time":"2015-12-13 21:29:14" },
      "R-daylightSaveTime": { "Value":"on", "Time":"2015-12-13 21:29:14" },
      "R-modePrioManu": { "Value":"all", "Time":"2015-12-13 21:29:14" },
      "R-modePrioParty": { "Value":"all", "Time":"2015-12-13 21:29:14" },
      "R-nightTemp": { "Value":"17 C", "Time":"2015-12-13 21:29:14" },
      "R-noMinMax4Manu": { "Value":"off", "Time":"2015-12-13 21:29:14" },
      "R-regAdaptive": { "Value":"on", "Time":"2015-12-13 21:29:14" },
      "R-showInfo": { "Value":"time", "Time":"2015-12-13 21:29:14" },
      "R-sign": { "Value":"off", "Time":"2015-12-13 21:26:22" },
      "R-tempOffset": { "Value":"0.0K", "Time":"2015-12-13 21:29:14" },
      "R-valveOffsetRt": { "Value":"0 %", "Time":"2015-12-13 21:29:14" },
      "R-winOpnBoost": { "Value":"off", "Time":"2015-12-13 21:29:14" },
      "R_0_tempListSat": { "Value":"10:00 17.0 22:00 21.0 22:30 19.0 24:00 17.0", "Time":"2016-02-29 15:16:11" },
      "R_1_tempListSun": { "Value":"10:00 17.0 21:00 21.0 21:30 19.0 24:00 17.0", "Time":"2016-02-29 15:16:11" },
      "R_2_tempListMon": { "Value":"16:00 17.0 21:00 21.0 21:30 19.0 24:00 17.0", "Time":"2016-02-29 15:16:11" },
      "R_3_tempListTue": { "Value":"16:00 17.0 21:00 21.0 21:30 19.0 24:00 17.0", "Time":"2016-02-29 15:16:11" },
      "R_4_tempListWed": { "Value":"18:00 17.0 21:00 21.0 21:30 19.0 24:00 17.0", "Time":"2016-02-29 15:16:11" },
      "R_5_tempListThu": { "Value":"16:00 17.0 21:00 21.0 21:30 19.0 24:00 17.0", "Time":"2016-02-29 15:16:11" },
      "R_6_tempListFri": { "Value":"12:00 17.0 19:30 21.0 22:30 19.0 24:00 17.0", "Time":"2016-02-29 15:16:11" },
      "R_tempList_State": { "Value":"verified", "Time":"2016-02-29 15:16:11" },
      "RegL_01.": { "Value":"08:00 00:00", "Time":"2016-02-29 15:16:07" },
      "RegL_07.": { "Value":"01:2A 02:22 03:09 04:3D 05:18 06:03 07:00 08:16 09:07 0A:30 0B:00 0C:64 0D:0F 0E:05 0F:00 10:00 11:00 12:09 13:8E 14:44 15:78 16:55 17:08 18:4D 19:0E 1A:45 1B:20 1C:45 1D:20 1E:45 1F:20 20:45 21:20 22:45 23:20 24:45 25:20 26:45 27:20 28:45 29:20 2A:45 2B:20 2C:45 2D:20 2E:44 2F:78 30:54 31:FC 32:4D 33:02 34:45 35:20 36:45 37:20 38:45 39:20 3A:45 3B:20 3C:45 3D:20 3E:45 3F:20 40:45 41:20 42:45 43:20 44:45 45:20 46:45 47:20 48:44 49:C0 4A:54 4B:FC 4C:4D 4D:02 4E:45 4F:20 50:45 51:20 52:45 53:20 54:45 55:20 56:45 57:20 58:45 59:20 5A:45 5B:20 5C:45 5D:20 5E:45 5F:20 60:45 61:20 62:44 63:C0 64:54 65:FC 66:4D 67:02 68:45 69:20 6A:45 6B:20 6C:45 6D:20 6E:45 6F:20 70:45 71:20 72:45 73:20 74:45 75:20 76:45 77:20 78:45 79:20 7A:45 7B:20 7C:44 7D:D8 7E:54 7F:FC 80:4D 81:02 82:45 83:20 84:45 85:20 86:45 87:20 88:45 89:20 8A:45 8B:20 8C:45 8D:20 8E:45 8F:20 90:45 91:20 92:45 93:20 94:45 95:20 96:44 97:C0 98:54 99:FC 9A:4D 9B:02 9C:45 9D:20 9E:45 9F:20 A0:45 A1:20 A2:45 A3:20 A4:45 A5:20 A6:45 A7:20 A8:45 A9:20 AA:45 AB:20 AC:45 AD:20 AE:45 AF:20 B0:44 B1:90 B2:54 B3:EA B4:4D B5:0E B6:45 B7:20 B8:45 B9:20 BA:45 BB:20 BC:45 BD:20 BE:45 BF:20 C0:45 C1:20 C2:45 C3:20 C4:45 C5:20 C6:45 C7:20 C8:45 C9:20 CA:0F CB:1E CC:1E CD:0F CE:1E CF:1E 00:00", "Time":"2016-02-29 15:16:11" },
      "ValvePosition": { "Value":"0", "Time":"2016-08-25 11:17:53" },
      "boostTime": { "Value":"-", "Time":"2016-08-25 11:17:53" },
      "controlMode": { "Value":"manual", "Time":"2016-08-25 11:17:53" },
      "desired-temp": { "Value":"10.0", "Time":"2016-08-25 11:17:53" },
      "measured-temp": { "Value":"22.0", "Time":"2016-08-25 11:17:53" },
      "partyEnd": { "Value":"-", "Time":"2016-08-25 11:17:53" },
      "partyStart": { "Value":"-", "Time":"2016-08-25 11:17:53" },
      "partyTemp": { "Value":"-", "Time":"2016-08-25 11:17:53" },
      "recentStateType": { "Value":"ack", "Time":"2016-08-23 16:43:13" },
      "state": { "Value":"T: 22.0 desired: 10.0 valve: 0", "Time":"2016-08-25 11:17:53" }
    },
    "Attributes": {
      "genericDeviceType": "thermostat",
      "group": "Thermostat",
      "model": "HM-CC-RT-DN",
      "peerIDs": "00000000,",
      "room": "Homekit,Thermostate,Wohnzimmer"
    }
  }  ],
  "totalResultsReturned":2
}
```
I tried adding genericDeviceType but that didn't change a thing, it wasn't needed before.
homebridge runs on RPi2 with node 4.5.0, FHEM is up-to-date

**Comment by justme-1968** [comment]
sorry. the last merge went wrong. fixed now.
