### ISSUE TITLE
Error: Cannot find module 'commander' 

### ISSUE THREAD

**Issue by hvorragend** [justme-1968/homebridge-fhem#37]
_Ticket was originally created here: https://github.com/marcoraddatz/homebridge-docker/issues/35_

Each time I start my homebridge environment an error appears:

> Error: Cannot find module 'commander'

I am using docker and I have to restart the container and then the error disappears. Do you have an idea?

**docker-compose.yml**
```
    homebridge:
        container_name: homebridge
        expose:
            - "51826"
            - "5353"
        ports:
            - "51826:51826"
            - "5353:5353"
        image: marcoraddatz/homebridge:develop
        volumes:
            - ./homebridge/data/:/root/.homebridge
        network_mode: "host"
```

**install.sh**
```
#!/bin/bash

# This file gets executed as root, so you can use it to
# install or update any plugin dependencies.
# See https://github.com/marcoraddatz/homebridge-docker#installsh

npm install -g homebridge-fhem
```

**config.json**
```
{
  "bridge": {
    "name": "Homebridge FHEM",
    "username": "xx:xx:xx:xx:xx:3xx9",
    "port": 51826,
    "pin": "0xx-xx-xxx"
  },
  "platforms": [
    {
      "platform": "FHEM",
      "name": "FHEM",
      "server": "127.0.0.1",
      "port": "8083",
      "filter": "room=Homekit"
    }
  ],
  "accessories": []
}

```

**Error**
```
npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm http fetch GET 200 https://registry.npmjs.org/homebridge 261ms
npm http fetch GET 200 https://registry.npmjs.org/qrcode-terminal 17ms
npm http fetch GET 200 https://registry.npmjs.org/chalk 131ms
npm http fetch GET 200 https://registry.npmjs.org/commander 186ms
npm http fetch GET 200 https://registry.npmjs.org/semver 242ms
npm http fetch GET 200 https://registry.npmjs.org/hap-nodejs 298ms
npm http fetch GET 304 https://registry.npmjs.org/node-persist 415ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/ansi-styles 113ms
npm http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 362ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-ansi 406ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 450ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/supports-color 495ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 110ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/graceful-readlink 126ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/debug 147ms
npm http fetch GET 200 https://registry.npmjs.org/ip 224ms
npm http fetch GET 200 https://registry.npmjs.org/decimal.js 359ms
npm http fetch GET 304 https://registry.npmjs.org/buffer-shims 371ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/curve25519-n2 375ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mdns 551ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ed25519 599ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fast-srp-hap 643ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/nan 126ms
npm http fetch GET 304 https://registry.npmjs.org/bindings 172ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 117ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp 80ms
npm http fetch GET 304 https://registry.npmjs.org/q 215ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/minimist 77ms
npm http fetch GET 200 https://registry.npmjs.org/homebridge/-/homebridge-0.4.31.tgz 44ms
npm http fetch GET 200 https://registry.npmjs.org/qrcode-terminal/-/qrcode-terminal-0.11.0.tgz 57ms
npm http fetch GET 200 https://registry.npmjs.org/hap-nodejs/-/hap-nodejs-0.4.36.tgz 110ms
npm info lifecycle homebridge@0.4.29~preuninstall: homebridge@0.4.29
npm info lifecycle homebridge@0.4.29~uninstall: homebridge@0.4.29
npm info lifecycle homebridge@0.4.29~postuninstall: homebridge@0.4.29
npm info lifecycle hap-nodejs@0.4.33~preuninstall: hap-nodejs@0.4.33
npm info lifecycle hap-nodejs@0.4.33~uninstall: hap-nodejs@0.4.33
npm info lifecycle hap-nodejs@0.4.33~postuninstall: hap-nodejs@0.4.33
npm info lifecycle hap-nodejs@0.4.36~preinstall: hap-nodejs@0.4.36
npm info lifecycle qrcode-terminal@0.11.0~preinstall: qrcode-terminal@0.11.0
npm info lifecycle homebridge@0.4.31~preinstall: homebridge@0.4.31
npm info linkStuff hap-nodejs@0.4.36
npm info linkStuff qrcode-terminal@0.11.0
npm info linkStuff homebridge@0.4.31
npm info lifecycle hap-nodejs@0.4.36~install: hap-nodejs@0.4.36
npm info lifecycle qrcode-terminal@0.11.0~install: qrcode-terminal@0.11.0
npm info lifecycle homebridge@0.4.31~install: homebridge@0.4.31
npm info lifecycle hap-nodejs@0.4.36~postinstall: hap-nodejs@0.4.36
npm info lifecycle qrcode-terminal@0.11.0~postinstall: qrcode-terminal@0.11.0
npm info lifecycle homebridge@0.4.31~postinstall: homebridge@0.4.31

 ok 
npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm http fetch GET 200 https://registry.npmjs.org/homebridge-fhem 137ms
npm http fetch GET 200 https://registry.npmjs.org/request 19ms
npm http fetch GET 200 https://registry.npmjs.org/aws-sign2 25ms
npm http fetch GET 200 https://registry.npmjs.org/is-typedarray 17ms
npm http fetch GET 200 https://registry.npmjs.org/aws4 72ms
npm http fetch GET 200 https://registry.npmjs.org/extend 71ms
npm http fetch GET 200 https://registry.npmjs.org/caseless 74ms
npm http fetch GET 200 https://registry.npmjs.org/forever-agent 74ms
npm http fetch GET 200 https://registry.npmjs.org/combined-stream 76ms
npm http fetch GET 200 https://registry.npmjs.org/http-signature 72ms
npm http fetch GET 200 https://registry.npmjs.org/form-data 76ms
npm http fetch GET 200 https://registry.npmjs.org/isstream 33ms
npm http fetch GET 200 https://registry.npmjs.org/har-validator 78ms
npm http fetch GET 200 https://registry.npmjs.org/hawk 81ms
npm http fetch GET 200 https://registry.npmjs.org/json-stringify-safe 48ms
npm http fetch GET 200 https://registry.npmjs.org/oauth-sign 43ms
npm http fetch GET 200 https://registry.npmjs.org/performance-now 45ms
npm http fetch GET 200 https://registry.npmjs.org/mime-types 49ms
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 45ms
npm http fetch GET 200 https://registry.npmjs.org/stringstream 45ms
npm http fetch GET 200 https://registry.npmjs.org/qs 50ms
npm http fetch GET 200 https://registry.npmjs.org/tough-cookie 53ms
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 37ms
npm http fetch GET 200 https://registry.npmjs.org/uuid 27ms
npm http fetch GET 200 https://registry.npmjs.org/delayed-stream 20ms
npm http fetch GET 200 https://registry.npmjs.org/asynckit 17ms
npm http fetch GET 200 https://registry.npmjs.org/mime-db 18ms
npm http fetch GET 200 https://registry.npmjs.org/har-schema 18ms
npm http fetch GET 200 https://registry.npmjs.org/ajv 23ms
npm http fetch GET 200 https://registry.npmjs.org/fast-deep-equal 24ms
npm http fetch GET 200 https://registry.npmjs.org/fast-json-stable-stringify 23ms
npm http fetch GET 200 https://registry.npmjs.org/co 26ms
npm http fetch GET 200 https://registry.npmjs.org/json-schema-traverse 28ms
npm http fetch GET 200 https://registry.npmjs.org/sntp 22ms
npm http fetch GET 200 https://registry.npmjs.org/hoek 23ms
npm http fetch GET 200 https://registry.npmjs.org/boom 25ms
npm http fetch GET 200 https://registry.npmjs.org/cryptiles 25ms
npm http fetch GET 200 https://registry.npmjs.org/jsprim 20ms
npm http fetch GET 200 https://registry.npmjs.org/sshpk 20ms
npm http fetch GET 200 https://registry.npmjs.org/assert-plus 23ms
npm http fetch GET 200 https://registry.npmjs.org/verror 19ms
npm http fetch GET 200 https://registry.npmjs.org/extsprintf 20ms
npm http fetch GET 200 https://registry.npmjs.org/json-schema 25ms
npm http fetch GET 200 https://registry.npmjs.org/core-util-is 17ms
npm http fetch GET 200 https://registry.npmjs.org/tweetnacl 38ms
npm http fetch GET 200 https://registry.npmjs.org/asn1 40ms
npm http fetch GET 200 https://registry.npmjs.org/jsbn 45ms
npm http fetch GET 200 https://registry.npmjs.org/bcrypt-pbkdf 44ms
npm http fetch GET 200 https://registry.npmjs.org/dashdash 47ms
npm http fetch GET 200 https://registry.npmjs.org/getpass 47ms
npm http fetch GET 200 https://registry.npmjs.org/ecc-jsbn 47ms
npm http fetch GET 200 https://registry.npmjs.org/punycode 17ms
npm http fetch GET 200 https://registry.npmjs.org/hoek/-/hoek-4.2.0.tgz 214ms
npm http fetch GET 200 https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz 212ms
npm http fetch GET 200 https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz 228ms
npm http fetch GET 200 https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz 229ms
npm http fetch GET 200 https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz 228ms
npm http fetch GET 200 https://registry.npmjs.org/cryptiles/-/cryptiles-3.1.2.tgz 224ms
npm http fetch GET 200 https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz 223ms
npm http fetch GET 200 https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz 231ms
npm http fetch GET 200 https://registry.npmjs.org/co/-/co-4.6.0.tgz 229ms
npm http fetch GET 200 https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz 229ms
npm http fetch GET 200 https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz 230ms
npm http fetch GET 200 https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz 229ms
npm http fetch GET 200 https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz 227ms
npm http fetch GET 200 https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.0.0.tgz 229ms
npm http fetch GET 200 https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz 228ms
npm http fetch GET 200 https://registry.npmjs.org/boom/-/boom-5.2.0.tgz 227ms
npm http fetch GET 200 https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz 226ms
npm http fetch GET 200 https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz 226ms
npm http fetch GET 200 https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz 226ms
npm http fetch GET 200 https://registry.npmjs.org/boom/-/boom-4.3.1.tgz 229ms
npm http fetch GET 200 https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz 226ms
npm http fetch GET 200 https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz 236ms
npm http fetch GET 200 https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz 240ms
npm http fetch GET 200 https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz 237ms
npm http fetch GET 200 https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz 250ms
npm http fetch GET 200 https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz 247ms
npm http fetch GET 200 https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz 247ms
npm http fetch GET 200 https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz 244ms
npm http fetch GET 200 https://registry.npmjs.org/extend/-/extend-3.0.1.tgz 249ms
npm http fetch GET 200 https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz 251ms
npm http fetch GET 200 https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz 252ms
npm http fetch GET 200 https://registry.npmjs.org/form-data/-/form-data-2.3.1.tgz 246ms
npm http fetch GET 200 https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz 251ms
npm http fetch GET 200 https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz 251ms
npm http fetch GET 200 https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz 257ms
npm http fetch GET 200 https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz 263ms
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz 261ms
npm http fetch GET 200 https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz 263ms
npm http fetch GET 200 https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz 271ms
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz 269ms
npm http fetch GET 200 https://registry.npmjs.org/hawk/-/hawk-6.0.2.tgz 272ms
npm http fetch GET 200 https://registry.npmjs.org/sntp/-/sntp-2.1.0.tgz 276ms
npm http fetch GET 200 https://registry.npmjs.org/qs/-/qs-6.5.1.tgz 278ms
npm http fetch GET 200 https://registry.npmjs.org/verror/-/verror-1.10.0.tgz 274ms
npm http fetch GET 200 https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz 274ms
npm http fetch GET 200 https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.3.tgz 286ms
npm http fetch GET 200 https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz 284ms
npm http fetch GET 200 https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz 283ms
npm http fetch GET 200 https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz 290ms
npm http fetch GET 200 https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz 63ms
npm http fetch GET 200 https://registry.npmjs.org/homebridge-fhem/-/homebridge-fhem-0.3.7.tgz 65ms
npm http fetch GET 200 https://registry.npmjs.org/request/-/request-2.83.0.tgz 68ms
npm http fetch GET 200 https://registry.npmjs.org/ajv/-/ajv-5.3.0.tgz 342ms
npm info lifecycle asn1@0.2.3~preinstall: asn1@0.2.3
npm info lifecycle assert-plus@1.0.0~preinstall: assert-plus@1.0.0
npm info lifecycle asynckit@0.4.0~preinstall: asynckit@0.4.0
npm info lifecycle aws-sign2@0.7.0~preinstall: aws-sign2@0.7.0
npm info lifecycle aws4@1.6.0~preinstall: aws4@1.6.0
npm info lifecycle caseless@0.12.0~preinstall: caseless@0.12.0
npm info lifecycle co@4.6.0~preinstall: co@4.6.0
npm info lifecycle core-util-is@1.0.2~preinstall: core-util-is@1.0.2
npm info lifecycle dashdash@1.14.1~preinstall: dashdash@1.14.1
npm info lifecycle delayed-stream@1.0.0~preinstall: delayed-stream@1.0.0
npm info lifecycle combined-stream@1.0.5~preinstall: combined-stream@1.0.5
npm info lifecycle extend@3.0.1~preinstall: extend@3.0.1
npm info lifecycle extsprintf@1.3.0~preinstall: extsprintf@1.3.0
npm info lifecycle fast-deep-equal@1.0.0~preinstall: fast-deep-equal@1.0.0
npm info lifecycle fast-json-stable-stringify@2.0.0~preinstall: fast-json-stable-stringify@2.0.0
npm info lifecycle forever-agent@0.6.1~preinstall: forever-agent@0.6.1
npm info lifecycle getpass@0.1.7~preinstall: getpass@0.1.7
npm info lifecycle har-schema@2.0.0~preinstall: har-schema@2.0.0
npm info lifecycle hoek@4.2.0~preinstall: hoek@4.2.0
npm info lifecycle boom@4.3.1~preinstall: boom@4.3.1
npm info lifecycle boom@5.2.0~preinstall: boom@5.2.0
npm info lifecycle cryptiles@3.1.2~preinstall: cryptiles@3.1.2
npm info lifecycle is-typedarray@1.0.0~preinstall: is-typedarray@1.0.0
npm info lifecycle isstream@0.1.2~preinstall: isstream@0.1.2
npm info lifecycle jsbn@0.1.1~preinstall: jsbn@0.1.1
npm info lifecycle ecc-jsbn@0.1.1~preinstall: ecc-jsbn@0.1.1
npm info lifecycle json-schema@0.2.3~preinstall: json-schema@0.2.3
npm info lifecycle json-schema-traverse@0.3.1~preinstall: json-schema-traverse@0.3.1
npm info lifecycle ajv@5.3.0~preinstall: ajv@5.3.0
npm info lifecycle har-validator@5.0.3~preinstall: har-validator@5.0.3
npm info lifecycle json-stringify-safe@5.0.1~preinstall: json-stringify-safe@5.0.1
npm info lifecycle mime-db@1.30.0~preinstall: mime-db@1.30.0
npm info lifecycle mime-types@2.1.17~preinstall: mime-types@2.1.17
npm info lifecycle form-data@2.3.1~preinstall: form-data@2.3.1
npm info lifecycle oauth-sign@0.8.2~preinstall: oauth-sign@0.8.2
npm info lifecycle performance-now@2.1.0~preinstall: performance-now@2.1.0
npm info lifecycle punycode@1.4.1~preinstall: punycode@1.4.1
npm info lifecycle qs@6.5.1~preinstall: qs@6.5.1
npm info lifecycle safe-buffer@5.1.1~preinstall: safe-buffer@5.1.1
npm info lifecycle sntp@2.1.0~preinstall: sntp@2.1.0
npm info lifecycle hawk@6.0.2~preinstall: hawk@6.0.2
npm info lifecycle stringstream@0.0.5~preinstall: stringstream@0.0.5
npm info lifecycle tough-cookie@2.3.3~preinstall: tough-cookie@2.3.3
npm info lifecycle tunnel-agent@0.6.0~preinstall: tunnel-agent@0.6.0
npm info lifecycle tweetnacl@0.14.5~preinstall: tweetnacl@0.14.5
npm info lifecycle bcrypt-pbkdf@1.0.1~preinstall: bcrypt-pbkdf@1.0.1
npm info lifecycle sshpk@1.13.1~preinstall: sshpk@1.13.1
npm info lifecycle uuid@3.1.0~preinstall: uuid@3.1.0
npm info lifecycle verror@1.10.0~preinstall: verror@1.10.0
npm info lifecycle jsprim@1.4.1~preinstall: jsprim@1.4.1
npm info lifecycle homebridge-fhem@0.3.7~preinstall: homebridge-fhem@0.3.7
npm info lifecycle request@2.83.0~preinstall: request@2.83.0
npm info lifecycle http-signature@1.2.0~preinstall: http-signature@1.2.0
npm info linkStuff asn1@0.2.3
npm info linkStuff assert-plus@1.0.0
npm info linkStuff asynckit@0.4.0
npm info linkStuff aws-sign2@0.7.0
npm info linkStuff aws4@1.6.0
npm info linkStuff caseless@0.12.0
npm info linkStuff co@4.6.0
npm info linkStuff core-util-is@1.0.2
npm info linkStuff dashdash@1.14.1
npm info linkStuff delayed-stream@1.0.0
npm info linkStuff combined-stream@1.0.5
npm info linkStuff extend@3.0.1
npm info linkStuff extsprintf@1.3.0
npm info linkStuff fast-deep-equal@1.0.0
npm info linkStuff fast-json-stable-stringify@2.0.0
npm info linkStuff forever-agent@0.6.1
npm info linkStuff getpass@0.1.7
npm info linkStuff har-schema@2.0.0
npm info linkStuff hoek@4.2.0
npm info linkStuff boom@4.3.1
npm info linkStuff boom@5.2.0
npm info linkStuff cryptiles@3.1.2
npm info linkStuff is-typedarray@1.0.0
npm info linkStuff isstream@0.1.2
npm info linkStuff jsbn@0.1.1
npm info linkStuff ecc-jsbn@0.1.1
npm info linkStuff json-schema@0.2.3
npm info linkStuff json-schema-traverse@0.3.1
npm info linkStuff ajv@5.3.0
npm info linkStuff har-validator@5.0.3
npm info linkStuff json-stringify-safe@5.0.1
npm info linkStuff mime-db@1.30.0
npm info linkStuff mime-types@2.1.17
npm info linkStuff form-data@2.3.1
npm info linkStuff oauth-sign@0.8.2
npm info linkStuff performance-now@2.1.0
npm info linkStuff punycode@1.4.1
npm info linkStuff qs@6.5.1
npm info linkStuff safe-buffer@5.1.1
npm info linkStuff sntp@2.1.0
npm info linkStuff hawk@6.0.2
npm info linkStuff stringstream@0.0.5
npm info linkStuff tough-cookie@2.3.3
npm info linkStuff tunnel-agent@0.6.0
npm info linkStuff tweetnacl@0.14.5
npm info linkStuff bcrypt-pbkdf@1.0.1
npm info linkStuff sshpk@1.13.1
npm info linkStuff uuid@3.1.0
npm info linkStuff verror@1.10.0
npm info linkStuff jsprim@1.4.1
npm info linkStuff http-signature@1.2.0
npm info linkStuff request@2.83.0
npm info linkStuff homebridge-fhem@0.3.7
npm info lifecycle asn1@0.2.3~install: asn1@0.2.3
npm info lifecycle assert-plus@1.0.0~install: assert-plus@1.0.0
npm info lifecycle asynckit@0.4.0~install: asynckit@0.4.0
npm info lifecycle aws-sign2@0.7.0~install: aws-sign2@0.7.0
npm info lifecycle aws4@1.6.0~install: aws4@1.6.0
npm info lifecycle caseless@0.12.0~install: caseless@0.12.0
npm info lifecycle co@4.6.0~install: co@4.6.0
npm info lifecycle core-util-is@1.0.2~install: core-util-is@1.0.2
npm info lifecycle dashdash@1.14.1~install: dashdash@1.14.1
npm info lifecycle delayed-stream@1.0.0~install: delayed-stream@1.0.0
npm info lifecycle combined-stream@1.0.5~install: combined-stream@1.0.5
npm info lifecycle extend@3.0.1~install: extend@3.0.1
npm info lifecycle extsprintf@1.3.0~install: extsprintf@1.3.0
npm info lifecycle fast-deep-equal@1.0.0~install: fast-deep-equal@1.0.0
npm info lifecycle fast-json-stable-stringify@2.0.0~install: fast-json-stable-stringify@2.0.0
npm info lifecycle forever-agent@0.6.1~install: forever-agent@0.6.1
npm info lifecycle getpass@0.1.7~install: getpass@0.1.7
npm info lifecycle har-schema@2.0.0~install: har-schema@2.0.0
npm info lifecycle hoek@4.2.0~install: hoek@4.2.0
npm info lifecycle boom@4.3.1~install: boom@4.3.1
npm info lifecycle boom@5.2.0~install: boom@5.2.0
npm info lifecycle cryptiles@3.1.2~install: cryptiles@3.1.2
npm info lifecycle is-typedarray@1.0.0~install: is-typedarray@1.0.0
npm info lifecycle isstream@0.1.2~install: isstream@0.1.2
npm info lifecycle jsbn@0.1.1~install: jsbn@0.1.1
npm info lifecycle ecc-jsbn@0.1.1~install: ecc-jsbn@0.1.1
npm info lifecycle json-schema@0.2.3~install: json-schema@0.2.3
npm info lifecycle json-schema-traverse@0.3.1~install: json-schema-traverse@0.3.1
npm info lifecycle ajv@5.3.0~install: ajv@5.3.0
npm info lifecycle har-validator@5.0.3~install: har-validator@5.0.3
npm info lifecycle json-stringify-safe@5.0.1~install: json-stringify-safe@5.0.1
npm info lifecycle mime-db@1.30.0~install: mime-db@1.30.0
npm info lifecycle mime-types@2.1.17~install: mime-types@2.1.17
npm info lifecycle form-data@2.3.1~install: form-data@2.3.1
npm info lifecycle oauth-sign@0.8.2~install: oauth-sign@0.8.2
npm info lifecycle performance-now@2.1.0~install: performance-now@2.1.0
npm info lifecycle punycode@1.4.1~install: punycode@1.4.1
npm info lifecycle qs@6.5.1~install: qs@6.5.1
npm info lifecycle safe-buffer@5.1.1~install: safe-buffer@5.1.1
npm info lifecycle sntp@2.1.0~install: sntp@2.1.0
npm info lifecycle hawk@6.0.2~install: hawk@6.0.2
npm info lifecycle stringstream@0.0.5~install: stringstream@0.0.5
npm info lifecycle tough-cookie@2.3.3~install: tough-cookie@2.3.3
npm info lifecycle tunnel-agent@0.6.0~install: tunnel-agent@0.6.0
npm info lifecycle tweetnacl@0.14.5~install: tweetnacl@0.14.5
npm info lifecycle bcrypt-pbkdf@1.0.1~install: bcrypt-pbkdf@1.0.1
npm info lifecycle sshpk@1.13.1~install: sshpk@1.13.1
npm info lifecycle uuid@3.1.0~install: uuid@3.1.0
npm info lifecycle verror@1.10.0~install: verror@1.10.0
npm info lifecycle jsprim@1.4.1~install: jsprim@1.4.1
npm info lifecycle http-signature@1.2.0~install: http-signature@1.2.0
npm info lifecycle request@2.83.0~install: request@2.83.0
npm info lifecycle homebridge-fhem@0.3.7~install: homebridge-fhem@0.3.7
npm info lifecycle asn1@0.2.3~postinstall: asn1@0.2.3
npm info lifecycle assert-plus@1.0.0~postinstall: assert-plus@1.0.0
npm info lifecycle asynckit@0.4.0~postinstall: asynckit@0.4.0
npm info lifecycle aws-sign2@0.7.0~postinstall: aws-sign2@0.7.0
npm info lifecycle aws4@1.6.0~postinstall: aws4@1.6.0
npm info lifecycle caseless@0.12.0~postinstall: caseless@0.12.0
npm info lifecycle co@4.6.0~postinstall: co@4.6.0
npm info lifecycle core-util-is@1.0.2~postinstall: core-util-is@1.0.2
npm info lifecycle dashdash@1.14.1~postinstall: dashdash@1.14.1
npm info lifecycle delayed-stream@1.0.0~postinstall: delayed-stream@1.0.0
npm info lifecycle combined-stream@1.0.5~postinstall: combined-stream@1.0.5
npm info lifecycle extend@3.0.1~postinstall: extend@3.0.1
npm info lifecycle extsprintf@1.3.0~postinstall: extsprintf@1.3.0
npm info lifecycle fast-deep-equal@1.0.0~postinstall: fast-deep-equal@1.0.0
npm info lifecycle fast-json-stable-stringify@2.0.0~postinstall: fast-json-stable-stringify@2.0.0
npm info lifecycle forever-agent@0.6.1~postinstall: forever-agent@0.6.1
npm info lifecycle getpass@0.1.7~postinstall: getpass@0.1.7
npm info lifecycle har-schema@2.0.0~postinstall: har-schema@2.0.0
npm info lifecycle hoek@4.2.0~postinstall: hoek@4.2.0
npm info lifecycle boom@4.3.1~postinstall: boom@4.3.1
npm info lifecycle boom@5.2.0~postinstall: boom@5.2.0
npm info lifecycle cryptiles@3.1.2~postinstall: cryptiles@3.1.2
npm info lifecycle is-typedarray@1.0.0~postinstall: is-typedarray@1.0.0
npm info lifecycle isstream@0.1.2~postinstall: isstream@0.1.2
npm info lifecycle jsbn@0.1.1~postinstall: jsbn@0.1.1
npm info lifecycle ecc-jsbn@0.1.1~postinstall: ecc-jsbn@0.1.1
npm info lifecycle json-schema@0.2.3~postinstall: json-schema@0.2.3
npm info lifecycle json-schema-traverse@0.3.1~postinstall: json-schema-traverse@0.3.1
npm info lifecycle ajv@5.3.0~postinstall: ajv@5.3.0
npm info lifecycle har-validator@5.0.3~postinstall: har-validator@5.0.3
npm info lifecycle json-stringify-safe@5.0.1~postinstall: json-stringify-safe@5.0.1
npm info lifecycle mime-db@1.30.0~postinstall: mime-db@1.30.0
npm info lifecycle mime-types@2.1.17~postinstall: mime-types@2.1.17
npm info lifecycle form-data@2.3.1~postinstall: form-data@2.3.1
npm info lifecycle oauth-sign@0.8.2~postinstall: oauth-sign@0.8.2
npm info lifecycle performance-now@2.1.0~postinstall: performance-now@2.1.0
npm info lifecycle punycode@1.4.1~postinstall: punycode@1.4.1
npm info lifecycle qs@6.5.1~postinstall: qs@6.5.1
npm info lifecycle safe-buffer@5.1.1~postinstall: safe-buffer@5.1.1
npm info lifecycle sntp@2.1.0~postinstall: sntp@2.1.0
npm info lifecycle hawk@6.0.2~postinstall: hawk@6.0.2
npm info lifecycle stringstream@0.0.5~postinstall: stringstream@0.0.5
npm info lifecycle tough-cookie@2.3.3~postinstall: tough-cookie@2.3.3
npm info lifecycle tunnel-agent@0.6.0~postinstall: tunnel-agent@0.6.0
npm info lifecycle tweetnacl@0.14.5~postinstall: tweetnacl@0.14.5
npm info lifecycle bcrypt-pbkdf@1.0.1~postinstall: bcrypt-pbkdf@1.0.1
npm info lifecycle sshpk@1.13.1~postinstall: sshpk@1.13.1
npm info lifecycle uuid@3.1.0~postinstall: uuid@3.1.0
npm info lifecycle verror@1.10.0~postinstall: verror@1.10.0
npm info lifecycle jsprim@1.4.1~postinstall: jsprim@1.4.1
npm info lifecycle http-signature@1.2.0~postinstall: http-signature@1.2.0
npm info lifecycle request@2.83.0~postinstall: request@2.83.0
npm info lifecycle homebridge-fhem@0.3.7~postinstall: homebridge-fhem@0.3.7

 ok 
module.js:529
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/cli.js:1:77)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by hvorragend** [comment]
Oh, I am sorry. It really seems to be another problem.
