### ISSUE TITLE
Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by tillsteinbach** [justme-1968/homebridge-fhem#5]
```
Homebridge is running on port 51826.
/usr/lib/node_modules/homebridge-fhem/index.js:877
                                        this.log.warn( 'genericDeviceType attribute was not known. please restart homebridge.' );
                                            ^

TypeError: Cannot read property 'log' of undefined
    at /usr/lib/node_modules/homebridge-fhem/index.js:877:45
    at Request._callback (/usr/lib/node_modules/homebridge-fhem/index.js:841:27)
    at Request.self.callback (/usr/lib/node_modules/homebridge-fhem/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at Gunzip.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
```

**Comment by tillsteinbach** [comment]
Line 879 is missing a ".bind(this)"

**Comment by justme-1968** [comment]
thanks.

have fixed it.
