### ISSUE TITLE
Homebridge zeigt Fehler 'toUpperCase'

### ISSUE THREAD

**Issue by DocVooDoo87** [justme-1968/homebridge-fhem#55]
Hi. I have just started the homebridge (homebridge -I) and got the following error. But this error has only just occurred. I did not make any changes, just updated npm.

Hallo. Ich habe gerade die Homebridge (homebridge -I) gestartet und die folgende Fehlermeldung erhalten. Dieser Fehler ist aber gerade erst aufgetreten. Ich habe keine Änderungen vorgenommen, sondern nur npm aktualisiert.

> [2019-5-25 13:42:01] TypeError: Cannot read property 'toUpperCase' of undefined
    at new FHEMAccessory (/usr/local/lib/node_modules/homebridge-fhem/index.js:1588:26)
    at FHEMPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:1174:42)
    at Array.map (<anonymous>)
    at FHEMPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:1171:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fhem/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
[2019-5-25 13:42:01] Got SIGTERM, shutting down Homebridge...

**Comment by DocVooDoo87** [comment]
i have reinstalled and the problem is fixed.

ich hab es deinstalliert, neugestartet, installiert und das problem war weg.

**Comment by justme-1968** [comment]
it was my mistake. i habe committed a version with a bug this morning and fixed it then in the afternoon.
