### ISSUE TITLE
Problems with version above 0.4.11

### ISSUE THREAD

**Issue by we5** [justme-1968/homebridge-fhem#58]
Hi there,

I just wanted to update to the latest version, but unfortunately an error is thrown in the console. So I went through the history of commits and releases and found the first release, that was causing this: `0.4.12`.

Below you can see the error. Is this something about Node.js version?

```
Oct 10 16:50:04 berry homebridge[29412]: [10/10/2019, 4:50:04 PM] Loaded plugin: homebridge-fhem
Oct 10 16:50:04 berry homebridge[29412]: homebridge API version: 2.4
Oct 10 16:50:04 berry homebridge[29412]: this is homebridge-fhem 0.4.12
Oct 10 16:50:04 berry homebridge[29412]: /usr/lib/node_modules/homebridge-fhem/node_modules/fakegato-history/lib/googleDrive.js:7
Oct 10 16:50:04 berry homebridge[29412]: const {google} = require('googleapis');
Oct 10 16:50:04 berry homebridge[29412]: ^
Oct 10 16:50:04 berry homebridge[29412]: SyntaxError: Unexpected token {
Oct 10 16:50:04 berry homebridge[29412]: at exports.runInThisContext (vm.js:53:16)
Oct 10 16:50:04 berry homebridge[29412]: at Module._compile (module.js:387:25)
Oct 10 16:50:04 berry homebridge[29412]: at Object.Module._extensions..js (module.js:422:10)
Oct 10 16:50:04 berry homebridge[29412]: at Module.load (module.js:357:32)
Oct 10 16:50:04 berry homebridge[29412]: at Function.Module._load (module.js:314:12)
Oct 10 16:50:04 berry homebridge[29412]: at Module.require (module.js:367:17)
Oct 10 16:50:04 berry homebridge[29412]: at require (internal/module.js:20:19)
Oct 10 16:50:04 berry homebridge[29412]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/fakegato-history/fakegato-storage.js:11:19)
Oct 10 16:50:04 berry homebridge[29412]: at Module._compile (module.js:413:34)
Oct 10 16:50:04 berry homebridge[29412]: at Object.Module._extensions..js (module.js:422:10)
```

**Comment by we5** [comment]
Yeah, thanks. I just upgraded also Node and it seems to work now. Sorry for bothering you first time.
