### ISSUE TITLE
Homebridge absturz - TypeError: value.match is not a function

### ISSUE THREAD

**Issue by Fillip38** [justme-1968/homebridge-fhem#60]
Hallo,
ich habe heute mein System einmal komplett neu aufgesetzt. Debian 10 mit FHEM und Co. Homebridge läuft soweit, nur homebridge-fhem macht Probleme. Wenn ich Diese der Home App hinzufügen will, stürtzt diese immer ab mit folgendem Hinweis:

> TypeError: value.match is not a function
    at FHEM_reading2homekit_ (/usr/lib/node_modules/homebridge-fhem/index.js:396:21)
    at FHEM_reading2homekit (/usr/lib/node_modules/homebridge-fhem/index.js:236:13)
    at /usr/lib/node_modules/homebridge-fhem/index.js:133:19
    at Array.forEach (<anonymous>)
    at FHEM_update (/usr/lib/node_modules/homebridge-fhem/index.js:126:19)
    at FHEMAccessory.<anonymous> (/usr/lib/node_modules/homebridge-fhem/index.js:2657:21)
    at Request._callback (/usr/lib/node_modules/homebridge-fhem/index.js:1063:27)
    at Request.self.callback (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:268:12)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1489:10)
    at Request.emit (events.js:310:20)
    at Gunzip.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1360:12)
    at Object.onceWrapper (events.js:416:28)
    at Gunzip.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Die Meldung(en) kommen bei den Xiaomi Kontaktsensoren...

Eine Idee wie ich das Problem beheben kann...?

**Comment by justme-1968** [comment]
zeig mal bitte das komplette log. am besten auch mit -D für debug starten.
