### ISSUE TITLE
warning from the characteristic 'Hue' & 'on'

### ISSUE THREAD

**Issue by Schwa-l-be** [justme-1968/homebridge-fhem#76]
Receiving two errors with devices for 'hue' and 'on'

`[22.2.2021, 13:44:43] [homebridge-fhem] This plugin generated a warning from the characteristic 'On': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
[22.2.2021, 13:44:43] [homebridge-fhem] Error: 
    at On.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2063:79)
    at On.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1839:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.<anonymous> (/usr/lib/node_modules/homebridge-fhem/index.js:2664:25)
    at Request._callback (/usr/lib/node_modules/homebridge-fhem/index.js:1063:27)
    at Request.self.callback (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:268:12)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1532:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1403:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[22.2.2021, 13:44:43] [FHEM]   value: 
  2021-02-22 13:44:43 caching: Stehlampe-hue: 
[22.2.2021, 13:44:43] [FHEM] Stehlampe-hue value  scaled to: NaN
[22.2.2021, 13:44:43] [FHEM] Stehlampe-hue value  scaled to: NaN
[22.2.2021, 13:44:43] [FHEM] Stehlampe-hue not a number: 
[22.2.2021, 13:44:43] [FHEM] Stehlampe-hue not a number: 
[22.2.2021, 13:44:43] [homebridge-fhem] This plugin generated a warning from the characteristic 'Hue': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
[22.2.2021, 13:44:43] [homebridge-fhem] Error: 
    at Hue.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2063:79)
    at Hue.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1839:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.<anonymous> (/usr/lib/node_modules/homebridge-fhem/index.js:2664:25)
    at Request._callback (/usr/lib/node_modules/homebridge-fhem/index.js:1063:27)
    at Request.self.callback (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:268:12)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1532:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1403:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

**Comment by justme-1968** [comment]
please include the log lines with the fhem event that created these values and a list of the fhem device.

**Comment by Schwa-l-be** [comment]
the device is
`setuuid Stehlampe 5f2d5856-f33f-5c6a-ab9e-31574ed391c48cd5
attr Stehlampe IODev FritzBox
attr Stehlampe alias Stehlampe
attr Stehlampe event-min-interval power:120
attr Stehlampe genericDeviceType light
attr Stehlampe room FBDECT,HomeKit,Wohnzimmer`

and the fhem log:
`2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_RSSI: 100
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Heap: 26
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Time: 2021-03-03T13:13:16
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_AP: 1
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 SleepMode: Dynamic
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_Signal: -50
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 UptimeSec: 4225479
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 LoadAvg: 19
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Speed: 1
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_Channel: 6
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Scheme: 0
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 MqttCount: 153
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Uptime: 48T21:44:39
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Sleep: 50
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_Downtime: 0T00:02:52
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 LedTable: on
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_BSSId: XX:XX:XX:A8:20:91
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Fade: off
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_SSId: XXXX
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_LinkCount: 97
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A LoadAvg: 19
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A UptimeSec: 966338
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_Signal: -67
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_Channel: 1
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A MqttCount: 17
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_AP: 1
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_RSSI: 66
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Heap: 27
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Time: 2021-03-03T13:13:17
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A SleepMode: Dynamic
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A POWER: ON
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_BSSId: XX:XX:14:2B:C9:B8
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_SSId: XXX
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_LinkCount: 4
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Uptime: 11T04:25:38
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Sleep: 50
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_Downtime: 0T00:00:54
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Factor: 0.16
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Today: 0.708
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Period: 9
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_TotalStartTime: 2020-09-21T08:40:55
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_ApparentPower: 14
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Current: 0.063
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Time: 2021-03-03T13:13:17
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_ReactivePower: 14
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Total: 7.706
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Yesterday: 0.000
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Power: 2
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Voltage: 224`

**Comment by Schwa-l-be** [comment]
the device is
`setuuid Stehlampe 5f2d5856-f33f-5c6a-ab9e-31574ed391c48cd5
attr Stehlampe IODev FritzBox
attr Stehlampe alias Stehlampe
attr Stehlampe event-min-interval power:120
attr Stehlampe genericDeviceType light
attr Stehlampe room FBDECT,HomeKit,Wohnzimmer`

and the fhem log:
`2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_RSSI: 100
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Heap: 26
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Time: 2021-03-03T13:13:16
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_AP: 1
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 SleepMode: Dynamic
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_Signal: -50
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 UptimeSec: 4225479
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 LoadAvg: 19
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Speed: 1
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_Channel: 6
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Scheme: 0
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 MqttCount: 153
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Uptime: 48T21:44:39
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Sleep: 50
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_Downtime: 0T00:02:52
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 LedTable: on
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_BSSId: DC:39:6F:A8:20:91
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Fade: off
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_SSId: FritzBox
2021-03-03 13:13:16 MQTT2_DEVICE MQTT2_DVES_CC3390 Wifi_LinkCount: 97
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A LoadAvg: 19
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A UptimeSec: 966338
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_Signal: -67
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_Channel: 1
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A MqttCount: 17
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_AP: 1
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_RSSI: 66
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Heap: 27
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Time: 2021-03-03T13:13:17
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A SleepMode: Dynamic
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A POWER: ON
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_BSSId: C8:0E:14:2B:C9:B8
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_SSId: X
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_LinkCount: 4
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Uptime: 11T04:25:38
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Sleep: 50
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Wifi_Downtime: 0T00:00:54
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Factor: 0.16
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Today: 0.708
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Period: 9
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_TotalStartTime: 2020-09-21T08:40:55
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_ApparentPower: 14
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Current: 0.063
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A Time: 2021-03-03T13:13:17
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_ReactivePower: 14
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Total: 7.706
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Yesterday: 0.000
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Power: 2
2021-03-03 13:13:17 MQTT2_DEVICE MQTT2_DVES_C6655A ENERGY_Voltage: 224`

**Comment by justme-1968** [comment]
please post a real list from the device with the list command.

**Comment by Schwa-l-be** [comment]
--

**Comment by Schwa-l-be** [comment]
Internals:
   DEF        FritzBox:13077_0010222_1 HANFUNUnit,switch,dimmer,colorswitch,lightSwitch
   FUUID      5f2d5856-f33f-5c6a-ab9e-31574ed391c48cd5
   FritzBox_MSGCNT 4018
   FritzBox_TIME 2021-03-03 14:16:35
   IODev      FritzBox
   LASTInputDev FritzBox
   MSGCNT     4018
   NAME       Stehlampe
   NR         43
   STATE      off
   TYPE       FBDECT
   colortemperature 3000
   id         13077_0010222_1
   props      HANFUNUnit,switch,dimmer,colorswitch,lightSwitch
READINGS:
     2021-03-03 14:16:35   AIN             13077 0010222-1
     2021-03-03 14:16:35   FBNAME          Stehlampe Wohnzimmer
     2021-03-03 14:16:35   FBPROP          HANFUNUnit,switch,dimmer,colorswitch,lightSwitch
     2021-03-03 14:16:35   FBTYPE          FRITZ!DECT 500
     2021-03-03 14:16:35   ID              2000
     2021-03-03 14:16:35   colormode       white
     2021-03-03 14:16:35   colortemperature 3000
     2021-03-03 14:16:35   colortemperaturemireds 333
     2021-03-03 14:16:35   current_mode    4
     2021-03-03 14:16:35   dim             53
     2021-03-03 14:16:35   etsideviceid    408
     2021-03-03 14:16:35   fwversion       0.0
     2021-03-03 14:16:35   level           136
     2021-03-03 14:16:35   present         yes
     2021-03-03 14:16:35   state           off
     2021-03-03 14:16:35   unittype        DIMMABLE_COLOR_BULB
Attributes:
   IODev      FritzBox
   alias      Stehlampe
   event-min-interval power:120
   genericDeviceType light
   room       FBDECT,HomeKit,Wohnzimmer

**Comment by justme-1968** [comment]
it looks like this is not a color device. please add a homebridgeMapping with Hue=clear
