### ISSUE TITLE
warning from the characteristic 'Saturation'

### ISSUE THREAD

**Issue by webdandy** [justme-1968/homebridge-fhem#77]
After upgrading to homebridge 1.3.1 and fhem 0.5.24 i receive the following warning:

Feb 26 07:55:51 SmartHome-Pi4.webdandy.local homebridge[2028]: [26.2.2021, 07:55:51] [homebridge-fhem] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.

also the following warning:

Mär 02 09:14:35 SmartHome-Pi4.webdandy.local homebridge[5975]: [2.3.2021, 09:14:35] [homebridge-fhem] This plugin generated a warning from the characteristic 'Hue': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.

**Comment by mueberall** [comment]
I have a similar issue:
[homebridge-fhem] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

**Comment by justme-1968** [comment]
please run homebridge with -D for more output and provide a list of the fhem device

**Comment by webdandy** [comment]
[3.3.2021, 19:40:40] [homebridge-fhem] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.
[3.3.2021, 19:40:40] [homebridge-fhem] Error: 
    at Saturation.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at Saturation.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1970:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:2664:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-fhem/index.js:1063:27)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:268:12)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1532:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1403:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by webdandy** [comment]
And the second error:

[3.3.2021, 19:45:01] [homebridge-fhem] This plugin generated a warning from the characteristic 'Hue': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.
[3.3.2021, 19:45:01] [homebridge-fhem] Error: 
    at Hue.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at Hue.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1970:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:2664:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-fhem/index.js:1063:27)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:268:12)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1532:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1403:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[3.3.2021, 19:45:01] [FHEM]   value:

**Comment by justme-1968** [comment]
and a list of the fhem device

**Comment by mueberall** [comment]
Here is the debug output. But don't know which device is causing the error. Seems to be the plugin homebridge-fhem.
[3/3/2021, 20:52:39] [homebridge-fhem] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/3/2021, 20:52:39] [homebridge-fhem] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:2664:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-fhem/index.js:1063:27)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:268:12)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1532:10)
    at Request.emit (events.js:314:20)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1403:12)
    at Object.onceWrapper (events.js:420:28)
    at Gunzip.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by webdandy** [comment]
> and a list of the fhem device

How do I get the list?

**Comment by justme-1968** [comment]
with the fhem list command

**Comment by webdandy** [comment]
> with the fhem list command

Is this output from room Homekit enough:

Ankleidezimmer_Beleuchtung
Ankleidezimmer_off
Baby_SOS_on_off
Badezimmer_Beleuchtung
Fuettern_on_off
HUEDevice22
HUEDevice28
HUEDevice32
HUEDevice33
HUEGroup3
Kinderzimmer_Beleuchtung
Kinderzimmer_off
Kueche_off
Kuechen_Beleuchtung
Licht_on_off
Lueften
MinkeMau_NAS_wol
Relais_Flurbeleuchtung
Romantik_Kinderzimmer_on_off
Romantik_Schlafzimmer_on_off
Romantik_Wohnzimmer_on_off
Schlafzimmer_Beleuchtung
Schlafzimmer_off
Steckdose_Drucker
Steckdose_Heizluefter
Steckdose_Heizstrahler
Steckdose_Klimaanlage
Steckdose_Lichterkette
Steckdose_Steffi
Steckdose_Stehlampe
Steckdose_TV_WZ
Steckdose_Unterbauschrank
Steckdose_Webcam
Steckdose_Weihnachtsbeleuchtung
WC_Beleuchtung
Wohnung_off
Wohnzimmer_Beleuchtung_Sw_01
Wohnzimmer_Beleuchtung_Sw_02
Wohnzimmer_off
kodi_restart_wz

**Comment by justme-1968** [comment]
this is a group and not a single device. a group has no readings of its own. so they can't be transmitted and you get an error.

use the createGroupReadings atribute to create the readings.

**Comment by webdandy** [comment]
> this is a group and not a single device. a group has no readings of its own. so they can't be transmitted and you get an error.
> 
> use the createGroupReadings atribute to create the readings.

Könntest Du mir bitte ein paar mehr Details geben?
Habe im Forum einen Beitrag gefunden, bin mir aber unsicher.
Muss ich bei der Bridge createGroupReadings auf 1 setzen und bei der Gruppe createGroupReadings auf 0?
Muss ich sinst noch etwas machen?
Vielen Dank

**Comment by justme-1968** [comment]
je nach dem was du erreichen willst. probier es einfach aus. es geht nichts kaputt.

für alle gruppen -> nur bei der. bridge auf 1 setzen reicht.
für eine bestimmte gruppe -> in der bridge auf 0 und in dieser einen gruppe auf 1

**Comment by webdandy** [comment]
ah super, danke! jetzt bekomme ich auch endlich bei Gruppen einen Status angezeigt ;-)
Das ging früher nicht.
Allerdings bekomme ich in der homebridge immer noch den 'Hue' Fehler.
Woran könnte dies jetzt noch liegen?

[5.3.2021, 14:58:02] [FHEM] HUEGroup3-hue value  scaled to: NaN
[5.3.2021, 14:58:02] [FHEM] HUEGroup3-hue not a number: 
[5.3.2021, 14:58:02] [homebridge-fhem] This plugin generated a warning from the characteristic 'Hue': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.
[5.3.2021, 14:58:02] [homebridge-fhem] Error: 
    at Hue.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at Hue.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1970:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:2664:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-fhem/index.js:1063:27)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:268:12)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1532:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1403:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by justme-1968** [comment]
zeig ein list vom device

**Comment by webdandy** [comment]
Internals:
   DEF        group 3  IODev=HueBridge
   FUUID      5c4486e6-f33f-88c1-2d5b-cdbcfa50c5445d8e
   FVERSION   31_HUEDevice.pm:0.238190/2021-02-24
   ID         G3
   INTERVAL   
   IODev      HueBridge
   NAME       HUEGroup3
   NR         497
   STATE      off
   TYPE       HUEDevice
   class      Kitchen
   lights     9,10
   name       Küchen Unterbauleuchten
   type       Room
   READINGS:
     2021-03-05 15:48:24   alert           select
     2021-03-05 15:48:24   all_on          0
     2021-03-05 15:48:24   any_on          0
     2021-03-05 15:48:24   bri             254
     2021-03-05 15:48:24   colormode       
     2021-03-05 15:48:24   ct              0
     2021-03-05 15:48:24   effect          
     2021-03-05 15:48:24   onoff           0
     2021-03-05 15:48:24   pct             0
     2021-03-05 15:48:24   reachable       1
     2021-03-05 15:48:24   sat             0
     2021-03-05 15:48:24   state           off
   helper:
     alert      select
     bri        254
     colormode  
     ct         0
     devtype    G
     effect     
     onoff      0
     pct        0
     reachable  1
     sat        0
     state      off
     update_timeout 1
     json:
       class      Kitchen
       name       Küchen Unterbauleuchten
       type       Room
       action:
         alert      select
         bri        254
       lights:
         9
         10
       sensors:
       state:
     lights:
       10         1
       9          1
Attributes:
   IODev      HueBridge
   alias      Küchen Unterbauleuchten
   color-icons 2
   delayedUpdate 1
   devStateIcon {(HUEDevice_devStateIcon($name),"toggle")}
   group      Licht
   icon       light_led
   room       HUEDevice,Homekit,Küche,Wohnung
   sortby     7
   userattr   createActionReadings:1,0 createGroupReadings:1,0
   webCmd     pct:on:off

**Comment by justme-1968** [comment]
da sind keine farbingen lampen mit in der gruppe. setz mal das attribut subType auf ctdimmer

**Comment by webdandy** [comment]
Besten Dank, das wars! Danke für die Hilfe. Habs aber auf dimmer gesetzt, wie die einzelnen Lampen schon waren.
Schönes Wochenende!
