### ISSUE TITLE
Homebridge-fhem Problem mit fhem Zugriff.

### ISSUE THREAD

**Issue by RolfM671** [justme-1968/homebridge-fhem#80]
Hallo an alle,
habe Probleme mit der Steuerung eines Shelly2.5 in fhem über homebridge-fhem zu steuern, wahrscheinlich hat es mit dem Fehler im Log zu tun. Nach Abarbeitung aller Hinweise im Log habe ich gelesen das ich den Entwickler des Plugins benachrichtigen soll, was ich hiermit mache. Ich hoffe das Logfile ist OK.
`Loading logs using native method...
File: /var/lib/homebridge/homebridge.log

[24.4.2021, 22:19:55] [Homebridge UI] Homebridge log truncated by admin.
[24.4.2021, 22:20:03] [FHEM] query: CurrentPosition for MarkiseTerrasse-pct
[24.4.2021, 22:20:03] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:20:03] [FHEM] query: TargetPosition for MarkiseTerrasse-pct
[24.4.2021, 22:20:03] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:20:03] [FHEM] query: Custom Current for MarkiseTerrasse-current
[24.4.2021, 22:20:03] [FHEM]   not cached
[24.4.2021, 22:20:03] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=%7BReadingsVal(%22MarkiseTerrasse%22,%22current%22,%22%22)%7D&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:20:03] [FHEM] query: Custom Power for MarkiseTerrasse-power
[24.4.2021, 22:20:03] [FHEM]   cached: 0 (as number)
[24.4.2021, 22:20:03] [FHEM] query: Custom Energy for MarkiseTerrasse-energy
[24.4.2021, 22:20:03] [FHEM]   cached: 1629 (as number)
[24.4.2021, 22:20:03] [FHEM] query: CurrentTemperature for MarkiseTerrasse-temperature
[24.4.2021, 22:20:03] [FHEM]   cached: 48.98 (as number)
[24.4.2021, 22:20:03] [FHEM]   value: stop
[24.4.2021, 22:20:03] [FHEM] MarkiseTerrasse-current not a number: stop
[24.4.2021, 22:20:03] [homebridge-fhem] This plugin generated a warning from the characteristic 'Current': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[24.4.2021, 22:20:03] [FHEM] query: CurrentPosition for MarkiseTerrasse-pct
[24.4.2021, 22:20:03] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:20:03] [FHEM] query: TargetPosition for MarkiseTerrasse-pct
[24.4.2021, 22:20:03] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:20:03] [FHEM] query: CurrentTemperature for MarkiseTerrasse-temperature
[24.4.2021, 22:20:03] [FHEM]   cached: 48.98 (as number)
[24.4.2021, 22:20:06] [FHEM] query: CurrentPosition for MarkiseTerrasse-pct
[24.4.2021, 22:20:06] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:20:06] [FHEM] query: TargetPosition for MarkiseTerrasse-pct
[24.4.2021, 22:20:06] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:20:06] [FHEM] query: CurrentTemperature for MarkiseTerrasse-temperature
[24.4.2021, 22:20:06] [FHEM]   cached: 48.98 (as number)
[24.4.2021, 22:20:08] [Homebridge UI] Homebridge restart request received
[24.4.2021, 22:20:08] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[24.4.2021, 22:20:08] [Homebridge UI] Sending SIGTERM to Homebridge
[24.4.2021, 22:20:08] Got SIGTERM, shutting down Homebridge...
[24.4.2021, 22:20:13] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[24.4.2021, 22:20:18] [HB Supervisor] Restarting Homebridge...
[24.4.2021, 22:20:18] [HB Supervisor] Starting Homebridge with extra flags: -I
[24.4.2021, 22:20:18] [HB Supervisor] Started Homebridge v1.3.4 with PID: 1011
Initializing HAP-NodeJS v0.9.4...
[24.4.2021, 22:20:19] Loaded config.json with 0 accessories and 2 platforms.
[24.4.2021, 22:20:19] Loaded 0 cached accessories from cachedAccessories.
[24.4.2021, 22:20:19] ---
[24.4.2021, 22:20:20] Loaded plugin: homebridge-config-ui-x@4.41.0
[24.4.2021, 22:20:20] Registering platform 'homebridge-config-ui-x.config'
[24.4.2021, 22:20:20] ---
[24.4.2021, 22:20:20] Loaded plugin: homebridge-fhem@0.5.30
homebridge API version: 2.7
this is homebridge-fhem 0.5.30
[24.4.2021, 22:20:22] Registering platform 'homebridge-fhem.FHEM'
[24.4.2021, 22:20:22] ---
[24.4.2021, 22:20:22] Loading 2 platforms...
[24.4.2021, 22:20:22] [Config] Initializing config platform...
[24.4.2021, 22:20:22] [Config] Running in Service Mode
[24.4.2021, 22:20:22] [FHEM] Initializing FHEM platform...
starting longpoll: https://192.168.xxx.xx:8083/fhem?XHR=1&inform=type=status;addglobal=1;filter=.*;since=null;fmt=JSON&timestamp=1619295622844
Server listening on: http://<ip>:8282
[24.4.2021, 22:20:22] [FHEM] Checking devices and attributes...
[24.4.2021, 22:20:22] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=%7BAttrVal(%22global%22,%22userattr%22,%22%22)%7D&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:20:22] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=jsonlist2%20TYPE=siri&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:20:23] [FHEM] siri device is siri
[24.4.2021, 22:20:23] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=%7B$defs%7Bsiri%7D-%3E%7B%22homebridge-fhem%20version%22%7D%20=%20%220.5.30%22%7D&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:20:23] [FHEM] Fetching FHEM devices...
[24.4.2021, 22:20:23] [FHEM] fetching: https://192.168.xxx.xx:8083/fhem?cmd=jsonlist2%20room%3DHomekit&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:20:23] [FHEM] got: 2 results
[24.4.2021, 22:20:23] [FHEM] MarkiseTerrasse is blind
[24.4.2021, 22:20:23] [FHEM] MarkiseTerrasse has
[24.4.2021, 22:20:23] [FHEM]   Custom Current [current]
[24.4.2021, 22:20:23] [FHEM]   Custom Power [power]
[24.4.2021, 22:20:23] [FHEM]   Custom Energy [energy]
[24.4.2021, 22:20:23] [FHEM]   CurrentPosition [pct]
[24.4.2021, 22:20:23] [FHEM]   TargetPosition [pct]
[24.4.2021, 22:20:23] [FHEM]   CurrentTemperature [temperature]
  2021-04-24 22:20:23 caching: MarkiseTerrasse-current: stop
[24.4.2021, 22:20:23] [FHEM] MarkiseTerrasse-current not a number: stop
  2021-04-24 22:20:23 caching: MarkiseTerrasse-power: 0.00
[24.4.2021, 22:20:23] [FHEM]     caching: Power: 0 (as number; from '0.00')
  2021-04-24 22:20:23 caching: MarkiseTerrasse-energy: 1629
[24.4.2021, 22:20:23] [FHEM]     caching: Energy: 1629 (as number; from '1629')
  2021-04-24 22:20:23 caching: MarkiseTerrasse-pct: 100
[24.4.2021, 22:20:23] [FHEM]     caching: CurrentPosition: 100 (as number; from '100')
[24.4.2021, 22:20:23] [FHEM]     caching: TargetPosition: 100 (as number; from '100')
  2021-04-24 22:20:23 caching: MarkiseTerrasse-temperature: 48.98
[24.4.2021, 22:20:23] [FHEM]     caching: CurrentTemperature: 48.98 (as number; from '48.98')
[24.4.2021, 22:20:23] [FHEM] siri: no service type detected
[24.4.2021, 22:20:23] [FHEM] no accessory created for siri (siri)
[24.4.2021, 22:20:23] Initializing platform accessory 'MarkiseTerrasse'...
[24.4.2021, 22:20:23] [FHEM] creating services for MarkiseTerrasse
[24.4.2021, 22:20:23] [FHEM]   information service for MarkiseTerrasse
[24.4.2021, 22:20:23] [FHEM]     manufacturer, model and serial number characteristics for MarkiseTerrasse
[24.4.2021, 22:20:23] [FHEM]     name (siriName) characteristic for MarkiseTerrasse
[24.4.2021, 22:20:23] [FHEM]   WindowCovering service for MarkiseTerrasse
[24.4.2021, 22:20:23] [FHEM]     Custom Current characteristic for MarkiseTerrasse:current
[24.4.2021, 22:20:23] [FHEM]     Custom Power characteristic for MarkiseTerrasse:power
[24.4.2021, 22:20:23] [FHEM]     Custom Energy characteristic for MarkiseTerrasse:energy
[24.4.2021, 22:20:23] [FHEM]     CurrentPosition characteristic for MarkiseTerrasse:pct
[24.4.2021, 22:20:23] [FHEM]     TargetPosition characteristic for MarkiseTerrasse:pct
[24.4.2021, 22:20:23] [FHEM]     CurrentTemperature characteristic for MarkiseTerrasse:temperature
Preparing Advertiser for 'Homebridge 3A25 5B15' using bonjour-hap backend!
Setup Payload:
X-HM://0023SUP59W0JS
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 000-00-000 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 3A25 5B15' using bonjour-hap backend!
[24.4.2021, 22:20:23] Homebridge v1.3.4 (Homebridge 3A25) is running on port 51075.
[24.4.2021, 22:20:24] [FHEM] query: CurrentPosition for MarkiseTerrasse-pct
[24.4.2021, 22:20:24] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:20:24] [FHEM] query: TargetPosition for MarkiseTerrasse-pct
[24.4.2021, 22:20:24] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:20:24] [FHEM] query: Custom Current for MarkiseTerrasse-current
[24.4.2021, 22:20:24] [FHEM]   not cached
[24.4.2021, 22:20:24] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=%7BReadingsVal(%22MarkiseTerrasse%22,%22current%22,%22%22)%7D&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:20:24] [FHEM] query: Custom Power for MarkiseTerrasse-power
[24.4.2021, 22:20:24] [FHEM]   cached: 0 (as number)
[24.4.2021, 22:20:24] [FHEM] query: Custom Energy for MarkiseTerrasse-energy
[24.4.2021, 22:20:24] [FHEM]   cached: 1629 (as number)
[24.4.2021, 22:20:24] [FHEM] query: CurrentTemperature for MarkiseTerrasse-temperature
[24.4.2021, 22:20:24] [FHEM]   cached: 48.98 (as number)
[24.4.2021, 22:20:24] [FHEM]   value: stop
[24.4.2021, 22:20:24] [FHEM] MarkiseTerrasse-current not a number: stop
[24.4.2021, 22:20:24] [homebridge-fhem] This plugin generated a warning from the characteristic 'Current': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[24.4.2021, 22:28:20] [Homebridge UI] Homebridge restart request received
[24.4.2021, 22:28:21] [Homebridge UI] No restart command defined, killing process...
[24.4.2021, 22:28:21] [HB Supervisor] Stopping services...
[24.4.2021, 22:28:21] Got SIGTERM, shutting down Homebridge...
[24.4.2021, 22:28:26] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[24.4.2021, 22:28:33] [HB Supervisor] OS: Linux 5.10.17-v7l+ arm
[24.4.2021, 22:28:33] [HB Supervisor] Node.js v14.16.0 /usr/local/bin/node
[24.4.2021, 22:28:33] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[24.4.2021, 22:28:33] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[24.4.2021, 22:28:37] [Homebridge UI] Homebridge Config UI X v4.41.0 is listening on :: port 8581
[24.4.2021, 22:28:37] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[24.4.2021, 22:28:37] [HB Supervisor] Started Homebridge v1.3.4 with PID: 1214
Initializing HAP-NodeJS v0.9.4...
[24.4.2021, 22:28:38] Loaded config.json with 0 accessories and 2 platforms.
[24.4.2021, 22:28:38] Loaded 0 cached accessories from cachedAccessories.
[24.4.2021, 22:28:38] ---
[24.4.2021, 22:28:39] Loaded plugin: homebridge-config-ui-x@4.41.0
[24.4.2021, 22:28:39] Registering platform 'homebridge-config-ui-x.config'
[24.4.2021, 22:28:39] ---
[24.4.2021, 22:28:39] Loaded plugin: homebridge-fhem@0.5.30
homebridge API version: 2.7
this is homebridge-fhem 0.5.30
[24.4.2021, 22:28:41] Registering platform 'homebridge-fhem.FHEM'
[24.4.2021, 22:28:41] ---
[24.4.2021, 22:28:41] Loading 2 platforms...
[24.4.2021, 22:28:41] [Config] Initializing config platform...
[24.4.2021, 22:28:41] [Config] Running in Service Mode
[24.4.2021, 22:28:41] [FHEM] Initializing FHEM platform...
starting longpoll: https://192.168.xxx.xx:8083/fhem?XHR=1&inform=type=status;addglobal=1;filter=.*;since=null;fmt=JSON&timestamp=1619296121655
[24.4.2021, 22:28:41] [FHEM] FHEM csrfToken missing, retry in: 500msec
Server listening on: http://<ip>:8282
[24.4.2021, 22:28:41] [FHEM] Checking devices and attributes...
[24.4.2021, 22:28:41] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=%7BAttrVal(%22global%22,%22userattr%22,%22%22)%7D&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:28:41] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=jsonlist2%20TYPE=siri&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:28:41] [FHEM] siri device is siri
[24.4.2021, 22:28:41] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=%7B$defs%7Bsiri%7D-%3E%7B%22homebridge-fhem%20version%22%7D%20=%20%220.5.30%22%7D&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:28:42] [FHEM] Fetching FHEM devices...
[24.4.2021, 22:28:42] [FHEM] fetching: https://192.168.xxx.xx:8083/fhem?cmd=jsonlist2%20room%3DHomekit&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:28:42] [FHEM] got: 2 results
[24.4.2021, 22:28:42] [FHEM] mappings for MarkiseTerrasse: {
  On: { reading: 'pct', valueOff: '0', cmdOn: 'on', cmdOff: 'off' },
  'E863F126-079E-48FF-8F27-9C2605A29F52': { name: 'Current', reading: 'current', format: 'FLOAT', factor: 1 },
  'E863F10D-079E-48FF-8F27-9C2605A29F52': { name: 'Power', reading: 'power', format: 'FLOAT', factor: 1 },
  'E863F10C-079E-48FF-8F27-9C2605A29F52': { name: 'Energy', reading: 'energy', format: 'FLOAT', factor: 1 },
  CurrentPosition: { reading: 'pct' },
  TargetPosition: { reading: 'pct', cmd: 'pct', delay: true },
  CurrentTemperature: { reading: 'temperature', minValue: -30 }
}
[24.4.2021, 22:28:42] [FHEM] MarkiseTerrasse is blind
[24.4.2021, 22:28:42] [FHEM] MarkiseTerrasse has
[24.4.2021, 22:28:42] [FHEM]   Custom Current [current]
[24.4.2021, 22:28:42] [FHEM]   Custom Power [power]
[24.4.2021, 22:28:42] [FHEM]   Custom Energy [energy]
[24.4.2021, 22:28:42] [FHEM]   CurrentPosition [pct]
[24.4.2021, 22:28:42] [FHEM]   TargetPosition [pct]
[24.4.2021, 22:28:42] [FHEM]   CurrentTemperature [temperature]
  2021-04-24 22:28:42 caching: MarkiseTerrasse-current: stop
[24.4.2021, 22:28:42] [FHEM] MarkiseTerrasse-current factor: value NaN mapped to NaN
[24.4.2021, 22:28:42] [FHEM] MarkiseTerrasse-current not a number: stop
  2021-04-24 22:28:42 caching: MarkiseTerrasse-power: 0.00
[24.4.2021, 22:28:42] [FHEM] MarkiseTerrasse-power factor: value 0 mapped to 0
[24.4.2021, 22:28:42] [FHEM]     caching: Power: 0 (as number; from '0.00')
  2021-04-24 22:28:42 caching: MarkiseTerrasse-energy: 1629
[24.4.2021, 22:28:42] [FHEM] MarkiseTerrasse-energy factor: value 1629 mapped to 1629
[24.4.2021, 22:28:42] [FHEM]     caching: Energy: 1629 (as number; from '1629')
  2021-04-24 22:28:42 caching: MarkiseTerrasse-pct: 100
[24.4.2021, 22:28:42] [FHEM]     caching: CurrentPosition: 100 (as number; from '100')
[24.4.2021, 22:28:42] [FHEM]     caching: TargetPosition: 100 (as number; from '100')
  2021-04-24 22:28:42 caching: MarkiseTerrasse-temperature: 48.98
[24.4.2021, 22:28:42] [FHEM]     caching: CurrentTemperature: 48.98 (as number; from '48.98')
[24.4.2021, 22:28:42] [FHEM] siri: no service type detected
[24.4.2021, 22:28:42] [FHEM] no accessory created for siri (siri)
[24.4.2021, 22:28:42] Initializing platform accessory 'MarkiseTerrasse'...
[24.4.2021, 22:28:42] [FHEM] creating services for MarkiseTerrasse
[24.4.2021, 22:28:42] [FHEM]   information service for MarkiseTerrasse
[24.4.2021, 22:28:42] [FHEM]     manufacturer, model and serial number characteristics for MarkiseTerrasse
[24.4.2021, 22:28:42] [FHEM]     name (siriName) characteristic for MarkiseTerrasse
[24.4.2021, 22:28:42] [FHEM]   WindowCovering service for MarkiseTerrasse
[24.4.2021, 22:28:42] [FHEM]     Custom Current characteristic for MarkiseTerrasse:current
[24.4.2021, 22:28:42] [FHEM]       no default
[24.4.2021, 22:28:42] [FHEM]       props: { format: 'float', perms: [ 'pr', 'ev' ] }
[24.4.2021, 22:28:42] [FHEM]     Custom Power characteristic for MarkiseTerrasse:power
[24.4.2021, 22:28:42] [FHEM]       initial value is: 0 (number)
[24.4.2021, 22:28:42] [FHEM]       props: { format: 'float', perms: [ 'pr', 'ev' ] }
[24.4.2021, 22:28:42] [FHEM]     Custom Energy characteristic for MarkiseTerrasse:energy
[24.4.2021, 22:28:42] [FHEM]       initial value is: 1629 (number)
[24.4.2021, 22:28:42] [FHEM]       props: { format: 'float', perms: [ 'pr', 'ev' ] }
[24.4.2021, 22:28:42] [FHEM]     CurrentPosition characteristic for MarkiseTerrasse:pct
[24.4.2021, 22:28:42] [FHEM]       initial value is: 100 (number)
[24.4.2021, 22:28:42] [FHEM]       props: {
  format: 'uint8',
  perms: [ 'ev', 'pr' ],
  unit: 'percentage',
  minValue: 0,
  maxValue: 100,
  minStep: 1
}
[24.4.2021, 22:28:42] [FHEM]     TargetPosition characteristic for MarkiseTerrasse:pct
[24.4.2021, 22:28:42] [FHEM]       initial value is: 100 (number)
[24.4.2021, 22:28:42] [FHEM]       props: {
  format: 'uint8',
  perms: [ 'ev', 'pr', 'pw' ],
  unit: 'percentage',
  minValue: 0,
  maxValue: 100,
  minStep: 1
}
[24.4.2021, 22:28:42] [FHEM]     CurrentTemperature characteristic for MarkiseTerrasse:temperature
[24.4.2021, 22:28:42] [FHEM]       initial value is: 48.98 (number)
[24.4.2021, 22:28:42] [FHEM]       props: {
  format: 'float',
  perms: [ 'ev', 'pr' ],
  unit: 'celsius',
  minValue: -30,
  maxValue: 100,
  minStep: 0.1
}
Preparing Advertiser for 'Homebridge 3A25 5B15' using bonjour-hap backend!
Setup Payload:
X-HM://0023SUP59W0JS
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 000-00-000 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 3A25 5B15' using bonjour-hap backend!
[24.4.2021, 22:28:42] Homebridge v1.3.4 (Homebridge 3A25) is running on port 51075.
[24.4.2021, 22:28:43] [FHEM] query: CurrentPosition for MarkiseTerrasse-pct
[24.4.2021, 22:28:43] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:28:43] [FHEM] query: TargetPosition for MarkiseTerrasse-pct
[24.4.2021, 22:28:43] [FHEM]   cached: 100 (as number)
[24.4.2021, 22:28:43] [FHEM] query: Custom Current for MarkiseTerrasse-current
[24.4.2021, 22:28:43] [FHEM]   not cached
[24.4.2021, 22:28:43] [FHEM]   executing: https://192.168.xxx.xx:8083/fhem?cmd=%7BReadingsVal(%22MarkiseTerrasse%22,%22current%22,%22%22)%7D&fwcsrf=csrf_278443981206159&XHR=1
[24.4.2021, 22:28:43] [FHEM] query: Custom Power for MarkiseTerrasse-power
[24.4.2021, 22:28:43] [FHEM]   cached: 0 (as number)
[24.4.2021, 22:28:43] [FHEM] query: Custom Energy for MarkiseTerrasse-energy
[24.4.2021, 22:28:43] [FHEM]   cached: 1629 (as number)
[24.4.2021, 22:28:43] [FHEM] query: CurrentTemperature for MarkiseTerrasse-temperature
[24.4.2021, 22:28:43] [FHEM]   cached: 48.98 (as number)
[24.4.2021, 22:28:43] [FHEM]   value: stop
[24.4.2021, 22:28:43] [FHEM] MarkiseTerrasse-current factor: value NaN mapped to NaN
[24.4.2021, 22:28:43] [homebridge-fhem] This plugin generated a warning from the characteristic 'Current': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[24.4.2021, 22:28:43] [homebridge-fhem] Error: 
    at Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:2690:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-fhem/index.js:1076:27)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:311:12)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1577:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1448:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[24.4.2021, 22:28:43] [FHEM] MarkiseTerrasse-current not a number: stop
`

**Comment by justme-1968** [comment]
dein homebridge mapping ist falsch bzw. unvollständig. der wert stop wird nicht behandelt.

**Comment by RolfM671** [comment]
Ja das habe ich schon gesehen das stop nicht erkannt wird. Wenn ich es also richtig verstehe ist das Problem das Template im MQTT, weil ich lese mit homebridge -fhem ja nur die Daten die mir fhem mittels MQTT bereit stellt. Kann man das so sehen?

**Comment by RolfM671** [comment]
Also soweit ich das jetzt nachverfolgt und beurteilen kann erwartet die Homebridge unter current eine Nummer, fhem-template liefert aber den Wert "Stop“ also keine Nummer. Was kann ich da machen?

**Comment by justme-1968** [comment]
das homebridgeMapping so ändern das eine passender wert draus wird.

am besten fragst du im forum. ich habe das template nicht im einsatz.
