### ISSUE TITLE
Thermostat's dont't work anymore

### ISSUE THREAD

**Issue by achimmm** [justme-1968/homebridge-fhem#83]
Hi,

after upgrading to Homebridge 1.3.0 I get the following erros just for thermostat devices.

The mentioned characteristic values should be okay, but for some reason a warning get's produced

```
[12/10/2021, 23:07:30] [FHEM] query: CurrentHeatingCoolingState for roomWohnzimmer2-undefined
[12/10/2021, 23:07:30] [FHEM]   cached: 1 (as number)
[12/10/2021, 23:07:30] [homebridge-fhem] This plugin generated a warning from the characteristic 'Current Heating Cooling State': Unhandled error thrown inside read handler for characteristic: Error: characteristic value 1 is not contained in valid values array!
    at CurrentHeatingCoolingState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2028:15)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.query (/usr/lib/node_modules/homebridge-fhem/index.js:2628:9)
    at FHEMAccessory.<anonymous> (/usr/lib/node_modules/homebridge-fhem/index.js:3149:31)
    at CurrentHeatingCoolingState.emit (events.js:400:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1466:14
    at new Promise (<anonymous>)
    at CurrentHeatingCoolingState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1464:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at CurrentHeatingCoolingState.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:632:24)
    at CurrentHeatingCoolingState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2127:22) See https://git.io/JtMGR for more info.
[12/10/2021, 23:07:30] [FHEM] query: TargetHeatingCoolingState for roomWohnzimmer2-undefined
[12/10/2021, 23:07:30] [FHEM]   cached: 3 (as number)
[12/10/2021, 23:07:30] [homebridge-fhem] This plugin generated a warning from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside read handler for characteristic: Error: characteristic value 3 is not contained in valid values array!
    at TargetHeatingCoolingState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2028:15)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at FHEMAccessory.query (/usr/lib/node_modules/homebridge-fhem/index.js:2628:9)
    at FHEMAccessory.<anonymous> (/usr/lib/node_modules/homebridge-fhem/index.js:3149:31)
    at TargetHeatingCoolingState.emit (events.js:400:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1466:14
    at new Promise (<anonymous>)
    at TargetHeatingCoolingState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1464:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at TargetHeatingCoolingState.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:632:24)
    at TargetHeatingCoolingState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2127:22) See https://git.io/JtMGR for more info.
```

**Comment by justme-1968** [comment]
please show a list of the fhem device. this is probably a missing/wrong homebridgeMapping.
